// AUTO-GENERATED by scripts/build-electricity-rates.ts — do not edit by hand.
// Source: EIA Form EIA-861M (Electric Power Monthly Table 5.6.A).
// "Average Price of Electricity to Ultimate Customers by End-Use Sector by State."
// Vintage: February 2026 (latest published).
// URL: https://www.eia.gov/electricity/monthly/xls/table_5_06_a.xlsx
//
// All values in cents per kilowatt-hour (¢/kWh).
//
// Veto #7 status: CLEAR — primary EIA Form EIA-861M, no synthesis.

export type ElectricityRateRow = {
  state: string;
  residential: number;
  commercial: number;
  industrial: number;
  allSectors: number;
};

export const ELECTRICITY_RATES_VINTAGE = '2026-02';
export const ELECTRICITY_RATES_SOURCE =
  'EIA Form EIA-861M, Electric Power Monthly Table 5.6.A (Feb 2026)';

export const ELECTRICITY_RATES: ReadonlyArray<ElectricityRateRow> = [
  { state: 'AK', residential: 25.79, commercial: 22.49, industrial: 20.81, allSectors: 23.31 },
  { state: 'AL', residential: 16.18, commercial: 15, industrial: 7.5, allSectors: 12.7 },
  { state: 'AR', residential: 12.73, commercial: 11.64, industrial: 6.4, allSectors: 10 },
  { state: 'AZ', residential: 16.03, commercial: 11.72, industrial: 7.07, allSectors: 12.29 },
  { state: 'CA', residential: 33.22, commercial: 24.73, industrial: 18.91, allSectors: 26.55 },
  { state: 'CO', residential: 16.79, commercial: 13.27, industrial: 9.38, allSectors: 13.44 },
  { state: 'CT', residential: 30.77, commercial: 24.59, industrial: 21.52, allSectors: 27.61 },
  { state: 'DC', residential: 23.97, commercial: 22.38, industrial: 22.72, allSectors: 22.7 },
  { state: 'DE', residential: 16.27, commercial: 14.5, industrial: 12.67, allSectors: 15.23 },
  { state: 'FL', residential: 15.8, commercial: 12.84, industrial: 9.51, allSectors: 14.31 },
  { state: 'GA', residential: 14.13, commercial: 12.02, industrial: 7.83, allSectors: 12.09 },
  { state: 'HI', residential: 43, commercial: 38.62, industrial: 33.24, allSectors: 37.78 },
  { state: 'IA', residential: 12.74, commercial: 10.74, industrial: 6.33, allSectors: 9.08 },
  { state: 'ID', residential: 12.63, commercial: 9.4, industrial: 7.17, allSectors: 10.14 },
  { state: 'IL', residential: 17.83, commercial: 13.33, industrial: 9.62, allSectors: 13.88 },
  { state: 'IN', residential: 16.06, commercial: 14.39, industrial: 9.59, allSectors: 13.21 },
  { state: 'KS', residential: 15.11, commercial: 11.74, industrial: 8.53, allSectors: 11.9 },
  { state: 'KY', residential: 13.42, commercial: 12.5, industrial: 7.64, allSectors: 11.25 },
  { state: 'LA', residential: 12.87, commercial: 12.17, industrial: 6.34, allSectors: 9.77 },
  { state: 'MA', residential: 30.46, commercial: 25.27, industrial: 21.45, allSectors: 27.06 },
  { state: 'MD', residential: 20.08, commercial: 18.11, industrial: 16.07, allSectors: 19.06 },
  { state: 'ME', residential: 32.17, commercial: 23.97, industrial: 18, allSectors: 26.67 },
  { state: 'MI', residential: 20, commercial: 15.15, industrial: 8.96, allSectors: 15.14 },
  { state: 'MN', residential: 15.39, commercial: 12.09, industrial: 9.33, allSectors: 12.52 },
  { state: 'MO', residential: 12.17, commercial: 9.86, industrial: 8.22, allSectors: 10.75 },
  { state: 'MS', residential: 14.72, commercial: 14.73, industrial: 7.54, allSectors: 12.32 },
  { state: 'MT', residential: 13.33, commercial: 12.52, industrial: 6.9, allSectors: 11.33 },
  { state: 'NC', residential: 14.64, commercial: 11.22, industrial: 8.55, allSectors: 12.55 },
  { state: 'ND', residential: 11.64, commercial: 8.08, industrial: 8.27, allSectors: 8.87 },
  { state: 'NE', residential: 11.79, commercial: 10.41, industrial: 6.09, allSectors: 9.49 },
  { state: 'NH', residential: 26.52, commercial: 22.92, industrial: 19.72, allSectors: 24.25 },
  { state: 'NJ', residential: 23.12, commercial: 17.29, industrial: 15.52, allSectors: 19.49 },
  { state: 'NM', residential: 15.07, commercial: 10.46, industrial: 5.65, allSectors: 8.97 },
  { state: 'NV', residential: 14.38, commercial: 8.96, industrial: 7.51, allSectors: 10.09 },
  { state: 'NY', residential: 29.99, commercial: 23.49, industrial: 10.92, allSectors: 24.88 },
  { state: 'OH', residential: 17.52, commercial: 14.3, industrial: 10.86, allSectors: 14.52 },
  { state: 'OK', residential: 12.89, commercial: 8.77, industrial: 6.28, allSectors: 9.36 },
  { state: 'OR', residential: 14.64, commercial: 10.68, industrial: 7.94, allSectors: 11.39 },
  { state: 'PA', residential: 20.3, commercial: 14.86, industrial: 11.88, allSectors: 16.52 },
  { state: 'RI', residential: 29.45, commercial: 24.06, industrial: 20.89, allSectors: 26.23 },
  { state: 'SC', residential: 16.15, commercial: 12.82, industrial: 8.62, allSectors: 13.1 },
  { state: 'SD', residential: 13.24, commercial: 11.19, industrial: 8.88, allSectors: 11.54 },
  { state: 'TN', residential: 12.82, commercial: 13.21, industrial: 6.8, allSectors: 11.73 },
  { state: 'TX', residential: 15.41, commercial: 8.9, industrial: 7.2, allSectors: 10.39 },
  { state: 'UT', residential: 13.33, commercial: 10.01, industrial: 8.44, allSectors: 10.65 },
  { state: 'VA', residential: 15.96, commercial: 13.01, industrial: 9.98, allSectors: 13.92 },
  { state: 'VT', residential: 23.27, commercial: 20.76, industrial: 13.67, allSectors: 20.42 },
  { state: 'WA', residential: 14.11, commercial: 12.23, industrial: 7.18, allSectors: 12.19 },
  { state: 'WI', residential: 18.74, commercial: 13.98, industrial: 9.13, allSectors: 13.95 },
  { state: 'WV', residential: 14.41, commercial: 11.75, industrial: 8.31, allSectors: 11.64 },
  { state: 'WY', residential: 13.04, commercial: 9.8, industrial: 9.1, allSectors: 10.12 },
];

const RATES_BY_STATE: Map<string, ElectricityRateRow> = new Map(
  ELECTRICITY_RATES.map((r) => [r.state, r]),
);

export function getElectricityRate(state: string): ElectricityRateRow | undefined {
  return RATES_BY_STATE.get(state.toUpperCase());
}

/**
 * National residential average (¢/kWh) for context.
 * Source: EIA Table 5.6.A "U.S. Total" residential row.
 */
export const US_RESIDENTIAL_RATE_AVG = 17.65;
