// AUTO-GENERATED by scripts/build-equivalent-pairs.ts — do not edit by hand.
// Source: BEA Regional Price Parities (MARPP) 2024.
// Top 200 metro pairs by absolute RPP gap, drawn from top-60 + bottom-10 RPP pool.
// Ratio interpretation: ratio_a_to_b = RPP_b / RPP_a, the multiplier on a salary
// when relocating A → B to maintain identical purchasing power.
//
// Veto #7 status: CLEAR — derivation from primary BEA RPP, no synthesis.

export type EquivalentPair = {
  pair_slug: string;
  slug_a: string;
  slug_b: string;
  fips_a: string;
  fips_b: string;
  name_a: string;
  name_b: string;
  state_a: string;
  state_b: string;
  rpp_a: number;
  rpp_b: number;
  ratio_a_to_b: number;
  ratio_b_to_a: number;
  gap_abs: number;
};

export const EQUIVALENT_PAIRS_VINTAGE = '2024';
export const EQUIVALENT_PAIRS_SOURCE =
  'BEA Regional Price Parities (MARPP), 2024 vintage';

export const EQUIVALENT_PAIRS: ReadonlyArray<EquivalentPair> = [
  // #1 gap 32.02
  { pair_slug: 'monroe-la-vs-san-francisco-oakland-fremont-ca', slug_a: 'monroe-la', slug_b: 'san-francisco-oakland-fremont-ca', fips_a: '33740', fips_b: '41860', name_a: "Monroe, LA", name_b: "San Francisco, CA", state_a: 'LA', state_b: 'CA', rpp_a: 83.597, rpp_b: 115.613, ratio_a_to_b: 1.383, ratio_b_to_a: 0.7231, gap_abs: 32.02 },
  // #2 gap 31.81
  { pair_slug: 'eagle-pass-tx-vs-san-francisco-oakland-fremont-ca', slug_a: 'eagle-pass-tx', slug_b: 'san-francisco-oakland-fremont-ca', fips_a: '20580', fips_b: '41860', name_a: "Eagle Pass, TX", name_b: "San Francisco, CA", state_a: 'TX', state_b: 'CA', rpp_a: 83.805, rpp_b: 115.613, ratio_a_to_b: 1.3795, ratio_b_to_a: 0.7249, gap_abs: 31.81 },
  // #3 gap 31.78
  { pair_slug: 'dothan-al-vs-san-francisco-oakland-fremont-ca', slug_a: 'dothan-al', slug_b: 'san-francisco-oakland-fremont-ca', fips_a: '20020', fips_b: '41860', name_a: "Dothan, AL", name_b: "San Francisco, CA", state_a: 'AL', state_b: 'CA', rpp_a: 83.833, rpp_b: 115.613, ratio_a_to_b: 1.3791, ratio_b_to_a: 0.7251, gap_abs: 31.78 },
  // #4 gap 31.60
  { pair_slug: 'san-francisco-oakland-fremont-ca-vs-texarkana-tx-ar', slug_a: 'san-francisco-oakland-fremont-ca', slug_b: 'texarkana-tx-ar', fips_a: '41860', fips_b: '45500', name_a: "San Francisco, CA", name_b: "Texarkana, TX", state_a: 'CA', state_b: 'TX', rpp_a: 115.613, rpp_b: 84.012, ratio_a_to_b: 0.7267, ratio_b_to_a: 1.3761, gap_abs: 31.6 },
  // #5 gap 31.34
  { pair_slug: 'enid-ok-vs-san-francisco-oakland-fremont-ca', slug_a: 'enid-ok', slug_b: 'san-francisco-oakland-fremont-ca', fips_a: '21420', fips_b: '41860', name_a: "Enid, OK *", name_b: "San Francisco, CA", state_a: 'OK', state_b: 'CA', rpp_a: 84.269, rpp_b: 115.613, ratio_a_to_b: 1.372, ratio_b_to_a: 0.7289, gap_abs: 31.34 },
  // #6 gap 31.15
  { pair_slug: 'hammond-la-vs-san-francisco-oakland-fremont-ca', slug_a: 'hammond-la', slug_b: 'san-francisco-oakland-fremont-ca', fips_a: '25220', fips_b: '41860', name_a: "Hammond, LA", name_b: "San Francisco, CA", state_a: 'LA', state_b: 'CA', rpp_a: 84.46, rpp_b: 115.613, ratio_a_to_b: 1.3688, ratio_b_to_a: 0.7305, gap_abs: 31.15 },
  // #7 gap 30.85
  { pair_slug: 'san-francisco-oakland-fremont-ca-vs-shreveport-bossier-city-la', slug_a: 'san-francisco-oakland-fremont-ca', slug_b: 'shreveport-bossier-city-la', fips_a: '41860', fips_b: '43340', name_a: "San Francisco, CA", name_b: "Shreveport, LA", state_a: 'CA', state_b: 'LA', rpp_a: 115.613, rpp_b: 84.766, ratio_a_to_b: 0.7332, ratio_b_to_a: 1.3639, gap_abs: 30.85 },
  // #8 gap 30.80
  { pair_slug: 'florence-muscle-shoals-al-vs-san-francisco-oakland-fremont-ca', slug_a: 'florence-muscle-shoals-al', slug_b: 'san-francisco-oakland-fremont-ca', fips_a: '22520', fips_b: '41860', name_a: "Florence, AL", name_b: "San Francisco, CA", state_a: 'AL', state_b: 'CA', rpp_a: 84.817, rpp_b: 115.613, ratio_a_to_b: 1.3631, ratio_b_to_a: 0.7336, gap_abs: 30.8 },
  // #9 gap 30.56
  { pair_slug: 'miami-fort-lauderdale-west-palm-beach-fl-vs-monroe-la', slug_a: 'miami-fort-lauderdale-west-palm-beach-fl', slug_b: 'monroe-la', fips_a: '33100', fips_b: '33740', name_a: "Miami, FL", name_b: "Monroe, LA", state_a: 'FL', state_b: 'LA', rpp_a: 114.155, rpp_b: 83.597, ratio_a_to_b: 0.7323, ratio_b_to_a: 1.3655, gap_abs: 30.56 },
  // #10 gap 30.51
  { pair_slug: 'houma-bayou-cane-thibodaux-la-vs-san-francisco-oakland-fremont-ca', slug_a: 'houma-bayou-cane-thibodaux-la', slug_b: 'san-francisco-oakland-fremont-ca', fips_a: '26380', fips_b: '41860', name_a: "Houma, LA", name_b: "San Francisco, CA", state_a: 'LA', state_b: 'CA', rpp_a: 85.103, rpp_b: 115.613, ratio_a_to_b: 1.3585, ratio_b_to_a: 0.7361, gap_abs: 30.51 },
  // #11 gap 30.35
  { pair_slug: 'eagle-pass-tx-vs-miami-fort-lauderdale-west-palm-beach-fl', slug_a: 'eagle-pass-tx', slug_b: 'miami-fort-lauderdale-west-palm-beach-fl', fips_a: '20580', fips_b: '33100', name_a: "Eagle Pass, TX", name_b: "Miami, FL", state_a: 'TX', state_b: 'FL', rpp_a: 83.805, rpp_b: 114.155, ratio_a_to_b: 1.3622, ratio_b_to_a: 0.7341, gap_abs: 30.35 },
  // #12 gap 30.32
  { pair_slug: 'dothan-al-vs-miami-fort-lauderdale-west-palm-beach-fl', slug_a: 'dothan-al', slug_b: 'miami-fort-lauderdale-west-palm-beach-fl', fips_a: '20020', fips_b: '33100', name_a: "Dothan, AL", name_b: "Miami, FL", state_a: 'AL', state_b: 'FL', rpp_a: 83.833, rpp_b: 114.155, ratio_a_to_b: 1.3617, ratio_b_to_a: 0.7344, gap_abs: 30.32 },
  // #13 gap 30.19
  { pair_slug: 'san-francisco-oakland-fremont-ca-vs-wildwood-the-villages-fl', slug_a: 'san-francisco-oakland-fremont-ca', slug_b: 'wildwood-the-villages-fl', fips_a: '41860', fips_b: '48680', name_a: "San Francisco, CA", name_b: "Wildwood, FL", state_a: 'CA', state_b: 'FL', rpp_a: 115.613, rpp_b: 85.424, ratio_a_to_b: 0.7389, ratio_b_to_a: 1.3534, gap_abs: 30.19 },
  // #14 gap 30.14
  { pair_slug: 'miami-fort-lauderdale-west-palm-beach-fl-vs-texarkana-tx-ar', slug_a: 'miami-fort-lauderdale-west-palm-beach-fl', slug_b: 'texarkana-tx-ar', fips_a: '33100', fips_b: '45500', name_a: "Miami, FL", name_b: "Texarkana, TX", state_a: 'FL', state_b: 'TX', rpp_a: 114.155, rpp_b: 84.012, ratio_a_to_b: 0.7359, ratio_b_to_a: 1.3588, gap_abs: 30.14 },
  // #15 gap 29.97
  { pair_slug: 'los-angeles-long-beach-anaheim-ca-vs-monroe-la', slug_a: 'los-angeles-long-beach-anaheim-ca', slug_b: 'monroe-la', fips_a: '31080', fips_b: '33740', name_a: "Los Angeles, CA", name_b: "Monroe, LA", state_a: 'CA', state_b: 'LA', rpp_a: 113.566, rpp_b: 83.597, ratio_a_to_b: 0.7361, ratio_b_to_a: 1.3585, gap_abs: 29.97 },
  // #16 gap 29.89
  { pair_slug: 'enid-ok-vs-miami-fort-lauderdale-west-palm-beach-fl', slug_a: 'enid-ok', slug_b: 'miami-fort-lauderdale-west-palm-beach-fl', fips_a: '21420', fips_b: '33100', name_a: "Enid, OK *", name_b: "Miami, FL", state_a: 'OK', state_b: 'FL', rpp_a: 84.269, rpp_b: 114.155, ratio_a_to_b: 1.3546, ratio_b_to_a: 0.7382, gap_abs: 29.89 },
  // #17 gap 29.76
  { pair_slug: 'eagle-pass-tx-vs-los-angeles-long-beach-anaheim-ca', slug_a: 'eagle-pass-tx', slug_b: 'los-angeles-long-beach-anaheim-ca', fips_a: '20580', fips_b: '31080', name_a: "Eagle Pass, TX", name_b: "Los Angeles, CA", state_a: 'TX', state_b: 'CA', rpp_a: 83.805, rpp_b: 113.566, ratio_a_to_b: 1.3551, ratio_b_to_a: 0.7379, gap_abs: 29.76 },
  // #18 gap 29.73
  { pair_slug: 'dothan-al-vs-los-angeles-long-beach-anaheim-ca', slug_a: 'dothan-al', slug_b: 'los-angeles-long-beach-anaheim-ca', fips_a: '20020', fips_b: '31080', name_a: "Dothan, AL", name_b: "Los Angeles, CA", state_a: 'AL', state_b: 'CA', rpp_a: 83.833, rpp_b: 113.566, ratio_a_to_b: 1.3547, ratio_b_to_a: 0.7382, gap_abs: 29.73 },
  // #19 gap 29.70
  { pair_slug: 'hammond-la-vs-miami-fort-lauderdale-west-palm-beach-fl', slug_a: 'hammond-la', slug_b: 'miami-fort-lauderdale-west-palm-beach-fl', fips_a: '25220', fips_b: '33100', name_a: "Hammond, LA", name_b: "Miami, FL", state_a: 'LA', state_b: 'FL', rpp_a: 84.46, rpp_b: 114.155, ratio_a_to_b: 1.3516, ratio_b_to_a: 0.7399, gap_abs: 29.7 },
  // #20 gap 29.55
  { pair_slug: 'los-angeles-long-beach-anaheim-ca-vs-texarkana-tx-ar', slug_a: 'los-angeles-long-beach-anaheim-ca', slug_b: 'texarkana-tx-ar', fips_a: '31080', fips_b: '45500', name_a: "Los Angeles, CA", name_b: "Texarkana, TX", state_a: 'CA', state_b: 'TX', rpp_a: 113.566, rpp_b: 84.012, ratio_a_to_b: 0.7398, ratio_b_to_a: 1.3518, gap_abs: 29.55 },
  // #21 gap 29.39
  { pair_slug: 'miami-fort-lauderdale-west-palm-beach-fl-vs-shreveport-bossier-city-la', slug_a: 'miami-fort-lauderdale-west-palm-beach-fl', slug_b: 'shreveport-bossier-city-la', fips_a: '33100', fips_b: '43340', name_a: "Miami, FL", name_b: "Shreveport, LA", state_a: 'FL', state_b: 'LA', rpp_a: 114.155, rpp_b: 84.766, ratio_a_to_b: 0.7426, ratio_b_to_a: 1.3467, gap_abs: 29.39 },
  // #22 gap 29.34
  { pair_slug: 'florence-muscle-shoals-al-vs-miami-fort-lauderdale-west-palm-beach-fl', slug_a: 'florence-muscle-shoals-al', slug_b: 'miami-fort-lauderdale-west-palm-beach-fl', fips_a: '22520', fips_b: '33100', name_a: "Florence, AL", name_b: "Miami, FL", state_a: 'AL', state_b: 'FL', rpp_a: 84.817, rpp_b: 114.155, ratio_a_to_b: 1.3459, ratio_b_to_a: 0.743, gap_abs: 29.34 },
  // #23 gap 29.30
  { pair_slug: 'enid-ok-vs-los-angeles-long-beach-anaheim-ca', slug_a: 'enid-ok', slug_b: 'los-angeles-long-beach-anaheim-ca', fips_a: '21420', fips_b: '31080', name_a: "Enid, OK *", name_b: "Los Angeles, CA", state_a: 'OK', state_b: 'CA', rpp_a: 84.269, rpp_b: 113.566, ratio_a_to_b: 1.3477, ratio_b_to_a: 0.742, gap_abs: 29.3 },
  // #24 gap 29.11
  { pair_slug: 'hammond-la-vs-los-angeles-long-beach-anaheim-ca', slug_a: 'hammond-la', slug_b: 'los-angeles-long-beach-anaheim-ca', fips_a: '25220', fips_b: '31080', name_a: "Hammond, LA", name_b: "Los Angeles, CA", state_a: 'LA', state_b: 'CA', rpp_a: 84.46, rpp_b: 113.566, ratio_a_to_b: 1.3446, ratio_b_to_a: 0.7437, gap_abs: 29.11 },
  // #25 gap 29.05
  { pair_slug: 'houma-bayou-cane-thibodaux-la-vs-miami-fort-lauderdale-west-palm-beach-fl', slug_a: 'houma-bayou-cane-thibodaux-la', slug_b: 'miami-fort-lauderdale-west-palm-beach-fl', fips_a: '26380', fips_b: '33100', name_a: "Houma, LA", name_b: "Miami, FL", state_a: 'LA', state_b: 'FL', rpp_a: 85.103, rpp_b: 114.155, ratio_a_to_b: 1.3414, ratio_b_to_a: 0.7455, gap_abs: 29.05 },
  // #26 gap 28.97
  { pair_slug: 'monroe-la-vs-new-york-newark-jersey-city-ny-nj', slug_a: 'monroe-la', slug_b: 'new-york-newark-jersey-city-ny-nj', fips_a: '33740', fips_b: '35620', name_a: "Monroe, LA", name_b: "New York, NY", state_a: 'LA', state_b: 'NY', rpp_a: 83.597, rpp_b: 112.563, ratio_a_to_b: 1.3465, ratio_b_to_a: 0.7427, gap_abs: 28.97 },
  // #27 gap 28.96
  { pair_slug: 'monroe-la-vs-napa-ca', slug_a: 'monroe-la', slug_b: 'napa-ca', fips_a: '33740', fips_b: '34900', name_a: "Monroe, LA", name_b: "Napa, CA", state_a: 'LA', state_b: 'CA', rpp_a: 83.597, rpp_b: 112.554, ratio_a_to_b: 1.3464, ratio_b_to_a: 0.7427, gap_abs: 28.96 },
  // #28 gap 28.80
  { pair_slug: 'los-angeles-long-beach-anaheim-ca-vs-shreveport-bossier-city-la', slug_a: 'los-angeles-long-beach-anaheim-ca', slug_b: 'shreveport-bossier-city-la', fips_a: '31080', fips_b: '43340', name_a: "Los Angeles, CA", name_b: "Shreveport, LA", state_a: 'CA', state_b: 'LA', rpp_a: 113.566, rpp_b: 84.766, ratio_a_to_b: 0.7464, ratio_b_to_a: 1.3398, gap_abs: 28.8 },
  // #29 gap 28.76
  { pair_slug: 'eagle-pass-tx-vs-new-york-newark-jersey-city-ny-nj', slug_a: 'eagle-pass-tx', slug_b: 'new-york-newark-jersey-city-ny-nj', fips_a: '20580', fips_b: '35620', name_a: "Eagle Pass, TX", name_b: "New York, NY", state_a: 'TX', state_b: 'NY', rpp_a: 83.805, rpp_b: 112.563, ratio_a_to_b: 1.3432, ratio_b_to_a: 0.7445, gap_abs: 28.76 },
  // #30 gap 28.75
  { pair_slug: 'florence-muscle-shoals-al-vs-los-angeles-long-beach-anaheim-ca', slug_a: 'florence-muscle-shoals-al', slug_b: 'los-angeles-long-beach-anaheim-ca', fips_a: '22520', fips_b: '31080', name_a: "Florence, AL", name_b: "Los Angeles, CA", state_a: 'AL', state_b: 'CA', rpp_a: 84.817, rpp_b: 113.566, ratio_a_to_b: 1.339, ratio_b_to_a: 0.7469, gap_abs: 28.75 },
  // #31 gap 28.75
  { pair_slug: 'eagle-pass-tx-vs-napa-ca', slug_a: 'eagle-pass-tx', slug_b: 'napa-ca', fips_a: '20580', fips_b: '34900', name_a: "Eagle Pass, TX", name_b: "Napa, CA", state_a: 'TX', state_b: 'CA', rpp_a: 83.805, rpp_b: 112.554, ratio_a_to_b: 1.343, ratio_b_to_a: 0.7446, gap_abs: 28.75 },
  // #32 gap 28.73
  { pair_slug: 'miami-fort-lauderdale-west-palm-beach-fl-vs-wildwood-the-villages-fl', slug_a: 'miami-fort-lauderdale-west-palm-beach-fl', slug_b: 'wildwood-the-villages-fl', fips_a: '33100', fips_b: '48680', name_a: "Miami, FL", name_b: "Wildwood, FL", state_a: 'FL', state_b: 'FL', rpp_a: 114.155, rpp_b: 85.424, ratio_a_to_b: 0.7483, ratio_b_to_a: 1.3363, gap_abs: 28.73 },
  // #33 gap 28.73
  { pair_slug: 'dothan-al-vs-new-york-newark-jersey-city-ny-nj', slug_a: 'dothan-al', slug_b: 'new-york-newark-jersey-city-ny-nj', fips_a: '20020', fips_b: '35620', name_a: "Dothan, AL", name_b: "New York, NY", state_a: 'AL', state_b: 'NY', rpp_a: 83.833, rpp_b: 112.563, ratio_a_to_b: 1.3427, ratio_b_to_a: 0.7448, gap_abs: 28.73 },
  // #34 gap 28.72
  { pair_slug: 'dothan-al-vs-napa-ca', slug_a: 'dothan-al', slug_b: 'napa-ca', fips_a: '20020', fips_b: '34900', name_a: "Dothan, AL", name_b: "Napa, CA", state_a: 'AL', state_b: 'CA', rpp_a: 83.833, rpp_b: 112.554, ratio_a_to_b: 1.3426, ratio_b_to_a: 0.7448, gap_abs: 28.72 },
  // #35 gap 28.55
  { pair_slug: 'new-york-newark-jersey-city-ny-nj-vs-texarkana-tx-ar', slug_a: 'new-york-newark-jersey-city-ny-nj', slug_b: 'texarkana-tx-ar', fips_a: '35620', fips_b: '45500', name_a: "New York, NY", name_b: "Texarkana, TX", state_a: 'NY', state_b: 'TX', rpp_a: 112.563, rpp_b: 84.012, ratio_a_to_b: 0.7464, ratio_b_to_a: 1.3398, gap_abs: 28.55 },
  // #36 gap 28.54
  { pair_slug: 'napa-ca-vs-texarkana-tx-ar', slug_a: 'napa-ca', slug_b: 'texarkana-tx-ar', fips_a: '34900', fips_b: '45500', name_a: "Napa, CA", name_b: "Texarkana, TX", state_a: 'CA', state_b: 'TX', rpp_a: 112.554, rpp_b: 84.012, ratio_a_to_b: 0.7464, ratio_b_to_a: 1.3397, gap_abs: 28.54 },
  // #37 gap 28.46
  { pair_slug: 'houma-bayou-cane-thibodaux-la-vs-los-angeles-long-beach-anaheim-ca', slug_a: 'houma-bayou-cane-thibodaux-la', slug_b: 'los-angeles-long-beach-anaheim-ca', fips_a: '26380', fips_b: '31080', name_a: "Houma, LA", name_b: "Los Angeles, CA", state_a: 'LA', state_b: 'CA', rpp_a: 85.103, rpp_b: 113.566, ratio_a_to_b: 1.3345, ratio_b_to_a: 0.7494, gap_abs: 28.46 },
  // #38 gap 28.29
  { pair_slug: 'enid-ok-vs-new-york-newark-jersey-city-ny-nj', slug_a: 'enid-ok', slug_b: 'new-york-newark-jersey-city-ny-nj', fips_a: '21420', fips_b: '35620', name_a: "Enid, OK *", name_b: "New York, NY", state_a: 'OK', state_b: 'NY', rpp_a: 84.269, rpp_b: 112.563, ratio_a_to_b: 1.3358, ratio_b_to_a: 0.7486, gap_abs: 28.29 },
  // #39 gap 28.29
  { pair_slug: 'monroe-la-vs-san-diego-chula-vista-carlsbad-ca', slug_a: 'monroe-la', slug_b: 'san-diego-chula-vista-carlsbad-ca', fips_a: '33740', fips_b: '41740', name_a: "Monroe, LA", name_b: "San Diego, CA", state_a: 'LA', state_b: 'CA', rpp_a: 83.597, rpp_b: 111.887, ratio_a_to_b: 1.3384, ratio_b_to_a: 0.7472, gap_abs: 28.29 },
  // #40 gap 28.28
  { pair_slug: 'enid-ok-vs-napa-ca', slug_a: 'enid-ok', slug_b: 'napa-ca', fips_a: '21420', fips_b: '34900', name_a: "Enid, OK *", name_b: "Napa, CA", state_a: 'OK', state_b: 'CA', rpp_a: 84.269, rpp_b: 112.554, ratio_a_to_b: 1.3357, ratio_b_to_a: 0.7487, gap_abs: 28.28 },
  // #41 gap 28.14
  { pair_slug: 'los-angeles-long-beach-anaheim-ca-vs-wildwood-the-villages-fl', slug_a: 'los-angeles-long-beach-anaheim-ca', slug_b: 'wildwood-the-villages-fl', fips_a: '31080', fips_b: '48680', name_a: "Los Angeles, CA", name_b: "Wildwood, FL", state_a: 'CA', state_b: 'FL', rpp_a: 113.566, rpp_b: 85.424, ratio_a_to_b: 0.7522, ratio_b_to_a: 1.3294, gap_abs: 28.14 },
  // #42 gap 28.10
  { pair_slug: 'hammond-la-vs-new-york-newark-jersey-city-ny-nj', slug_a: 'hammond-la', slug_b: 'new-york-newark-jersey-city-ny-nj', fips_a: '25220', fips_b: '35620', name_a: "Hammond, LA", name_b: "New York, NY", state_a: 'LA', state_b: 'NY', rpp_a: 84.46, rpp_b: 112.563, ratio_a_to_b: 1.3327, ratio_b_to_a: 0.7503, gap_abs: 28.1 },
  // #43 gap 28.09
  { pair_slug: 'hammond-la-vs-napa-ca', slug_a: 'hammond-la', slug_b: 'napa-ca', fips_a: '25220', fips_b: '34900', name_a: "Hammond, LA", name_b: "Napa, CA", state_a: 'LA', state_b: 'CA', rpp_a: 84.46, rpp_b: 112.554, ratio_a_to_b: 1.3326, ratio_b_to_a: 0.7504, gap_abs: 28.09 },
  // #44 gap 28.08
  { pair_slug: 'eagle-pass-tx-vs-san-diego-chula-vista-carlsbad-ca', slug_a: 'eagle-pass-tx', slug_b: 'san-diego-chula-vista-carlsbad-ca', fips_a: '20580', fips_b: '41740', name_a: "Eagle Pass, TX", name_b: "San Diego, CA", state_a: 'TX', state_b: 'CA', rpp_a: 83.805, rpp_b: 111.887, ratio_a_to_b: 1.3351, ratio_b_to_a: 0.749, gap_abs: 28.08 },
  // #45 gap 28.05
  { pair_slug: 'dothan-al-vs-san-diego-chula-vista-carlsbad-ca', slug_a: 'dothan-al', slug_b: 'san-diego-chula-vista-carlsbad-ca', fips_a: '20020', fips_b: '41740', name_a: "Dothan, AL", name_b: "San Diego, CA", state_a: 'AL', state_b: 'CA', rpp_a: 83.833, rpp_b: 111.887, ratio_a_to_b: 1.3346, ratio_b_to_a: 0.7493, gap_abs: 28.05 },
  // #46 gap 27.88
  { pair_slug: 'san-diego-chula-vista-carlsbad-ca-vs-texarkana-tx-ar', slug_a: 'san-diego-chula-vista-carlsbad-ca', slug_b: 'texarkana-tx-ar', fips_a: '41740', fips_b: '45500', name_a: "San Diego, CA", name_b: "Texarkana, TX", state_a: 'CA', state_b: 'TX', rpp_a: 111.887, rpp_b: 84.012, ratio_a_to_b: 0.7509, ratio_b_to_a: 1.3318, gap_abs: 27.88 },
  // #47 gap 27.80
  { pair_slug: 'new-york-newark-jersey-city-ny-nj-vs-shreveport-bossier-city-la', slug_a: 'new-york-newark-jersey-city-ny-nj', slug_b: 'shreveport-bossier-city-la', fips_a: '35620', fips_b: '43340', name_a: "New York, NY", name_b: "Shreveport, LA", state_a: 'NY', state_b: 'LA', rpp_a: 112.563, rpp_b: 84.766, ratio_a_to_b: 0.7531, ratio_b_to_a: 1.3279, gap_abs: 27.8 },
  // #48 gap 27.79
  { pair_slug: 'napa-ca-vs-shreveport-bossier-city-la', slug_a: 'napa-ca', slug_b: 'shreveport-bossier-city-la', fips_a: '34900', fips_b: '43340', name_a: "Napa, CA", name_b: "Shreveport, LA", state_a: 'CA', state_b: 'LA', rpp_a: 112.554, rpp_b: 84.766, ratio_a_to_b: 0.7531, ratio_b_to_a: 1.3278, gap_abs: 27.79 },
  // #49 gap 27.75
  { pair_slug: 'florence-muscle-shoals-al-vs-new-york-newark-jersey-city-ny-nj', slug_a: 'florence-muscle-shoals-al', slug_b: 'new-york-newark-jersey-city-ny-nj', fips_a: '22520', fips_b: '35620', name_a: "Florence, AL", name_b: "New York, NY", state_a: 'AL', state_b: 'NY', rpp_a: 84.817, rpp_b: 112.563, ratio_a_to_b: 1.3271, ratio_b_to_a: 0.7535, gap_abs: 27.75 },
  // #50 gap 27.74
  { pair_slug: 'florence-muscle-shoals-al-vs-napa-ca', slug_a: 'florence-muscle-shoals-al', slug_b: 'napa-ca', fips_a: '22520', fips_b: '34900', name_a: "Florence, AL", name_b: "Napa, CA", state_a: 'AL', state_b: 'CA', rpp_a: 84.817, rpp_b: 112.554, ratio_a_to_b: 1.327, ratio_b_to_a: 0.7536, gap_abs: 27.74 },
  // #51 gap 27.62
  { pair_slug: 'enid-ok-vs-san-diego-chula-vista-carlsbad-ca', slug_a: 'enid-ok', slug_b: 'san-diego-chula-vista-carlsbad-ca', fips_a: '21420', fips_b: '41740', name_a: "Enid, OK *", name_b: "San Diego, CA", state_a: 'OK', state_b: 'CA', rpp_a: 84.269, rpp_b: 111.887, ratio_a_to_b: 1.3277, ratio_b_to_a: 0.7532, gap_abs: 27.62 },
  // #52 gap 27.54
  { pair_slug: 'monroe-la-vs-seattle-tacoma-bellevue-wa', slug_a: 'monroe-la', slug_b: 'seattle-tacoma-bellevue-wa', fips_a: '33740', fips_b: '42660', name_a: "Monroe, LA", name_b: "Seattle, WA", state_a: 'LA', state_b: 'WA', rpp_a: 83.597, rpp_b: 111.133, ratio_a_to_b: 1.3294, ratio_b_to_a: 0.7522, gap_abs: 27.54 },
  // #53 gap 27.46
  { pair_slug: 'houma-bayou-cane-thibodaux-la-vs-new-york-newark-jersey-city-ny-nj', slug_a: 'houma-bayou-cane-thibodaux-la', slug_b: 'new-york-newark-jersey-city-ny-nj', fips_a: '26380', fips_b: '35620', name_a: "Houma, LA", name_b: "New York, NY", state_a: 'LA', state_b: 'NY', rpp_a: 85.103, rpp_b: 112.563, ratio_a_to_b: 1.3227, ratio_b_to_a: 0.756, gap_abs: 27.46 },
  // #54 gap 27.45
  { pair_slug: 'houma-bayou-cane-thibodaux-la-vs-napa-ca', slug_a: 'houma-bayou-cane-thibodaux-la', slug_b: 'napa-ca', fips_a: '26380', fips_b: '34900', name_a: "Houma, LA", name_b: "Napa, CA", state_a: 'LA', state_b: 'CA', rpp_a: 85.103, rpp_b: 112.554, ratio_a_to_b: 1.3226, ratio_b_to_a: 0.7561, gap_abs: 27.45 },
  // #55 gap 27.43
  { pair_slug: 'hammond-la-vs-san-diego-chula-vista-carlsbad-ca', slug_a: 'hammond-la', slug_b: 'san-diego-chula-vista-carlsbad-ca', fips_a: '25220', fips_b: '41740', name_a: "Hammond, LA", name_b: "San Diego, CA", state_a: 'LA', state_b: 'CA', rpp_a: 84.46, rpp_b: 111.887, ratio_a_to_b: 1.3247, ratio_b_to_a: 0.7549, gap_abs: 27.43 },
  // #56 gap 27.36
  { pair_slug: 'monroe-la-vs-urban-honolulu-hi', slug_a: 'monroe-la', slug_b: 'urban-honolulu-hi', fips_a: '33740', fips_b: '46520', name_a: "Monroe, LA", name_b: "Urban Honolulu, HI", state_a: 'LA', state_b: 'HI', rpp_a: 83.597, rpp_b: 110.961, ratio_a_to_b: 1.3273, ratio_b_to_a: 0.7534, gap_abs: 27.36 },
  // #57 gap 27.33
  { pair_slug: 'eagle-pass-tx-vs-seattle-tacoma-bellevue-wa', slug_a: 'eagle-pass-tx', slug_b: 'seattle-tacoma-bellevue-wa', fips_a: '20580', fips_b: '42660', name_a: "Eagle Pass, TX", name_b: "Seattle, WA", state_a: 'TX', state_b: 'WA', rpp_a: 83.805, rpp_b: 111.133, ratio_a_to_b: 1.3261, ratio_b_to_a: 0.7541, gap_abs: 27.33 },
  // #58 gap 27.30
  { pair_slug: 'dothan-al-vs-seattle-tacoma-bellevue-wa', slug_a: 'dothan-al', slug_b: 'seattle-tacoma-bellevue-wa', fips_a: '20020', fips_b: '42660', name_a: "Dothan, AL", name_b: "Seattle, WA", state_a: 'AL', state_b: 'WA', rpp_a: 83.833, rpp_b: 111.133, ratio_a_to_b: 1.3256, ratio_b_to_a: 0.7543, gap_abs: 27.3 },
  // #59 gap 27.16
  { pair_slug: 'eagle-pass-tx-vs-urban-honolulu-hi', slug_a: 'eagle-pass-tx', slug_b: 'urban-honolulu-hi', fips_a: '20580', fips_b: '46520', name_a: "Eagle Pass, TX", name_b: "Urban Honolulu, HI", state_a: 'TX', state_b: 'HI', rpp_a: 83.805, rpp_b: 110.961, ratio_a_to_b: 1.324, ratio_b_to_a: 0.7553, gap_abs: 27.16 },
  // #60 gap 27.14
  { pair_slug: 'new-york-newark-jersey-city-ny-nj-vs-wildwood-the-villages-fl', slug_a: 'new-york-newark-jersey-city-ny-nj', slug_b: 'wildwood-the-villages-fl', fips_a: '35620', fips_b: '48680', name_a: "New York, NY", name_b: "Wildwood, FL", state_a: 'NY', state_b: 'FL', rpp_a: 112.563, rpp_b: 85.424, ratio_a_to_b: 0.7589, ratio_b_to_a: 1.3177, gap_abs: 27.14 },
  // #61 gap 27.13
  { pair_slug: 'napa-ca-vs-wildwood-the-villages-fl', slug_a: 'napa-ca', slug_b: 'wildwood-the-villages-fl', fips_a: '34900', fips_b: '48680', name_a: "Napa, CA", name_b: "Wildwood, FL", state_a: 'CA', state_b: 'FL', rpp_a: 112.554, rpp_b: 85.424, ratio_a_to_b: 0.759, ratio_b_to_a: 1.3176, gap_abs: 27.13 },
  // #62 gap 27.13
  { pair_slug: 'dothan-al-vs-urban-honolulu-hi', slug_a: 'dothan-al', slug_b: 'urban-honolulu-hi', fips_a: '20020', fips_b: '46520', name_a: "Dothan, AL", name_b: "Urban Honolulu, HI", state_a: 'AL', state_b: 'HI', rpp_a: 83.833, rpp_b: 110.961, ratio_a_to_b: 1.3236, ratio_b_to_a: 0.7555, gap_abs: 27.13 },
  // #63 gap 27.12
  { pair_slug: 'san-diego-chula-vista-carlsbad-ca-vs-shreveport-bossier-city-la', slug_a: 'san-diego-chula-vista-carlsbad-ca', slug_b: 'shreveport-bossier-city-la', fips_a: '41740', fips_b: '43340', name_a: "San Diego, CA", name_b: "Shreveport, LA", state_a: 'CA', state_b: 'LA', rpp_a: 111.887, rpp_b: 84.766, ratio_a_to_b: 0.7576, ratio_b_to_a: 1.32, gap_abs: 27.12 },
  // #64 gap 27.12
  { pair_slug: 'seattle-tacoma-bellevue-wa-vs-texarkana-tx-ar', slug_a: 'seattle-tacoma-bellevue-wa', slug_b: 'texarkana-tx-ar', fips_a: '42660', fips_b: '45500', name_a: "Seattle, WA", name_b: "Texarkana, TX", state_a: 'WA', state_b: 'TX', rpp_a: 111.133, rpp_b: 84.012, ratio_a_to_b: 0.756, ratio_b_to_a: 1.3228, gap_abs: 27.12 },
  // #65 gap 27.07
  { pair_slug: 'florence-muscle-shoals-al-vs-san-diego-chula-vista-carlsbad-ca', slug_a: 'florence-muscle-shoals-al', slug_b: 'san-diego-chula-vista-carlsbad-ca', fips_a: '22520', fips_b: '41740', name_a: "Florence, AL", name_b: "San Diego, CA", state_a: 'AL', state_b: 'CA', rpp_a: 84.817, rpp_b: 111.887, ratio_a_to_b: 1.3192, ratio_b_to_a: 0.7581, gap_abs: 27.07 },
  // #66 gap 26.95
  { pair_slug: 'texarkana-tx-ar-vs-urban-honolulu-hi', slug_a: 'texarkana-tx-ar', slug_b: 'urban-honolulu-hi', fips_a: '45500', fips_b: '46520', name_a: "Texarkana, TX", name_b: "Urban Honolulu, HI", state_a: 'TX', state_b: 'HI', rpp_a: 84.012, rpp_b: 110.961, ratio_a_to_b: 1.3208, ratio_b_to_a: 0.7571, gap_abs: 26.95 },
  // #67 gap 26.94
  { pair_slug: 'monroe-la-vs-oxnard-thousand-oaks-ventura-ca', slug_a: 'monroe-la', slug_b: 'oxnard-thousand-oaks-ventura-ca', fips_a: '33740', fips_b: '37100', name_a: "Monroe, LA", name_b: "Oxnard, CA", state_a: 'LA', state_b: 'CA', rpp_a: 83.597, rpp_b: 110.534, ratio_a_to_b: 1.3222, ratio_b_to_a: 0.7563, gap_abs: 26.94 },
  // #68 gap 26.86
  { pair_slug: 'enid-ok-vs-seattle-tacoma-bellevue-wa', slug_a: 'enid-ok', slug_b: 'seattle-tacoma-bellevue-wa', fips_a: '21420', fips_b: '42660', name_a: "Enid, OK *", name_b: "Seattle, WA", state_a: 'OK', state_b: 'WA', rpp_a: 84.269, rpp_b: 111.133, ratio_a_to_b: 1.3188, ratio_b_to_a: 0.7583, gap_abs: 26.86 },
  // #69 gap 26.83
  { pair_slug: 'monroe-la-vs-san-jose-sunnyvale-santa-clara-ca', slug_a: 'monroe-la', slug_b: 'san-jose-sunnyvale-santa-clara-ca', fips_a: '33740', fips_b: '41940', name_a: "Monroe, LA", name_b: "San Jose, CA", state_a: 'LA', state_b: 'CA', rpp_a: 83.597, rpp_b: 110.423, ratio_a_to_b: 1.3209, ratio_b_to_a: 0.7571, gap_abs: 26.83 },
  // #70 gap 26.78
  { pair_slug: 'houma-bayou-cane-thibodaux-la-vs-san-diego-chula-vista-carlsbad-ca', slug_a: 'houma-bayou-cane-thibodaux-la', slug_b: 'san-diego-chula-vista-carlsbad-ca', fips_a: '26380', fips_b: '41740', name_a: "Houma, LA", name_b: "San Diego, CA", state_a: 'LA', state_b: 'CA', rpp_a: 85.103, rpp_b: 111.887, ratio_a_to_b: 1.3147, ratio_b_to_a: 0.7606, gap_abs: 26.78 },
  // #71 gap 26.73
  { pair_slug: 'eagle-pass-tx-vs-oxnard-thousand-oaks-ventura-ca', slug_a: 'eagle-pass-tx', slug_b: 'oxnard-thousand-oaks-ventura-ca', fips_a: '20580', fips_b: '37100', name_a: "Eagle Pass, TX", name_b: "Oxnard, CA", state_a: 'TX', state_b: 'CA', rpp_a: 83.805, rpp_b: 110.534, ratio_a_to_b: 1.3189, ratio_b_to_a: 0.7582, gap_abs: 26.73 },
  // #72 gap 26.70
  { pair_slug: 'dothan-al-vs-oxnard-thousand-oaks-ventura-ca', slug_a: 'dothan-al', slug_b: 'oxnard-thousand-oaks-ventura-ca', fips_a: '20020', fips_b: '37100', name_a: "Dothan, AL", name_b: "Oxnard, CA", state_a: 'AL', state_b: 'CA', rpp_a: 83.833, rpp_b: 110.534, ratio_a_to_b: 1.3185, ratio_b_to_a: 0.7584, gap_abs: 26.7 },
  // #73 gap 26.69
  { pair_slug: 'enid-ok-vs-urban-honolulu-hi', slug_a: 'enid-ok', slug_b: 'urban-honolulu-hi', fips_a: '21420', fips_b: '46520', name_a: "Enid, OK *", name_b: "Urban Honolulu, HI", state_a: 'OK', state_b: 'HI', rpp_a: 84.269, rpp_b: 110.961, ratio_a_to_b: 1.3167, ratio_b_to_a: 0.7594, gap_abs: 26.69 },
  // #74 gap 26.67
  { pair_slug: 'hammond-la-vs-seattle-tacoma-bellevue-wa', slug_a: 'hammond-la', slug_b: 'seattle-tacoma-bellevue-wa', fips_a: '25220', fips_b: '42660', name_a: "Hammond, LA", name_b: "Seattle, WA", state_a: 'LA', state_b: 'WA', rpp_a: 84.46, rpp_b: 111.133, ratio_a_to_b: 1.3158, ratio_b_to_a: 0.76, gap_abs: 26.67 },
  // #75 gap 26.62
  { pair_slug: 'eagle-pass-tx-vs-san-jose-sunnyvale-santa-clara-ca', slug_a: 'eagle-pass-tx', slug_b: 'san-jose-sunnyvale-santa-clara-ca', fips_a: '20580', fips_b: '41940', name_a: "Eagle Pass, TX", name_b: "San Jose, CA", state_a: 'TX', state_b: 'CA', rpp_a: 83.805, rpp_b: 110.423, ratio_a_to_b: 1.3176, ratio_b_to_a: 0.7589, gap_abs: 26.62 },
  // #76 gap 26.59
  { pair_slug: 'dothan-al-vs-san-jose-sunnyvale-santa-clara-ca', slug_a: 'dothan-al', slug_b: 'san-jose-sunnyvale-santa-clara-ca', fips_a: '20020', fips_b: '41940', name_a: "Dothan, AL", name_b: "San Jose, CA", state_a: 'AL', state_b: 'CA', rpp_a: 83.833, rpp_b: 110.423, ratio_a_to_b: 1.3172, ratio_b_to_a: 0.7592, gap_abs: 26.59 },
  // #77 gap 26.52
  { pair_slug: 'oxnard-thousand-oaks-ventura-ca-vs-texarkana-tx-ar', slug_a: 'oxnard-thousand-oaks-ventura-ca', slug_b: 'texarkana-tx-ar', fips_a: '37100', fips_b: '45500', name_a: "Oxnard, CA", name_b: "Texarkana, TX", state_a: 'CA', state_b: 'TX', rpp_a: 110.534, rpp_b: 84.012, ratio_a_to_b: 0.7601, ratio_b_to_a: 1.3157, gap_abs: 26.52 },
  // #78 gap 26.50
  { pair_slug: 'hammond-la-vs-urban-honolulu-hi', slug_a: 'hammond-la', slug_b: 'urban-honolulu-hi', fips_a: '25220', fips_b: '46520', name_a: "Hammond, LA", name_b: "Urban Honolulu, HI", state_a: 'LA', state_b: 'HI', rpp_a: 84.46, rpp_b: 110.961, ratio_a_to_b: 1.3138, ratio_b_to_a: 0.7612, gap_abs: 26.5 },
  // #79 gap 26.46
  { pair_slug: 'san-diego-chula-vista-carlsbad-ca-vs-wildwood-the-villages-fl', slug_a: 'san-diego-chula-vista-carlsbad-ca', slug_b: 'wildwood-the-villages-fl', fips_a: '41740', fips_b: '48680', name_a: "San Diego, CA", name_b: "Wildwood, FL", state_a: 'CA', state_b: 'FL', rpp_a: 111.887, rpp_b: 85.424, ratio_a_to_b: 0.7635, ratio_b_to_a: 1.3098, gap_abs: 26.46 },
  // #80 gap 26.41
  { pair_slug: 'san-jose-sunnyvale-santa-clara-ca-vs-texarkana-tx-ar', slug_a: 'san-jose-sunnyvale-santa-clara-ca', slug_b: 'texarkana-tx-ar', fips_a: '41940', fips_b: '45500', name_a: "San Jose, CA", name_b: "Texarkana, TX", state_a: 'CA', state_b: 'TX', rpp_a: 110.423, rpp_b: 84.012, ratio_a_to_b: 0.7608, ratio_b_to_a: 1.3144, gap_abs: 26.41 },
  // #81 gap 26.37
  { pair_slug: 'seattle-tacoma-bellevue-wa-vs-shreveport-bossier-city-la', slug_a: 'seattle-tacoma-bellevue-wa', slug_b: 'shreveport-bossier-city-la', fips_a: '42660', fips_b: '43340', name_a: "Seattle, WA", name_b: "Shreveport, LA", state_a: 'WA', state_b: 'LA', rpp_a: 111.133, rpp_b: 84.766, ratio_a_to_b: 0.7627, ratio_b_to_a: 1.3111, gap_abs: 26.37 },
  // #82 gap 26.32
  { pair_slug: 'florence-muscle-shoals-al-vs-seattle-tacoma-bellevue-wa', slug_a: 'florence-muscle-shoals-al', slug_b: 'seattle-tacoma-bellevue-wa', fips_a: '22520', fips_b: '42660', name_a: "Florence, AL", name_b: "Seattle, WA", state_a: 'AL', state_b: 'WA', rpp_a: 84.817, rpp_b: 111.133, ratio_a_to_b: 1.3103, ratio_b_to_a: 0.7632, gap_abs: 26.32 },
  // #83 gap 26.30
  { pair_slug: 'monroe-la-vs-santa-cruz-watsonville-ca', slug_a: 'monroe-la', slug_b: 'santa-cruz-watsonville-ca', fips_a: '33740', fips_b: '42100', name_a: "Monroe, LA", name_b: "Santa Cruz, CA", state_a: 'LA', state_b: 'CA', rpp_a: 83.597, rpp_b: 109.896, ratio_a_to_b: 1.3146, ratio_b_to_a: 0.7607, gap_abs: 26.3 },
  // #84 gap 26.27
  { pair_slug: 'enid-ok-vs-oxnard-thousand-oaks-ventura-ca', slug_a: 'enid-ok', slug_b: 'oxnard-thousand-oaks-ventura-ca', fips_a: '21420', fips_b: '37100', name_a: "Enid, OK *", name_b: "Oxnard, CA", state_a: 'OK', state_b: 'CA', rpp_a: 84.269, rpp_b: 110.534, ratio_a_to_b: 1.3117, ratio_b_to_a: 0.7624, gap_abs: 26.27 },
  // #85 gap 26.19
  { pair_slug: 'shreveport-bossier-city-la-vs-urban-honolulu-hi', slug_a: 'shreveport-bossier-city-la', slug_b: 'urban-honolulu-hi', fips_a: '43340', fips_b: '46520', name_a: "Shreveport, LA", name_b: "Urban Honolulu, HI", state_a: 'LA', state_b: 'HI', rpp_a: 84.766, rpp_b: 110.961, ratio_a_to_b: 1.309, ratio_b_to_a: 0.7639, gap_abs: 26.19 },
  // #86 gap 26.15
  { pair_slug: 'enid-ok-vs-san-jose-sunnyvale-santa-clara-ca', slug_a: 'enid-ok', slug_b: 'san-jose-sunnyvale-santa-clara-ca', fips_a: '21420', fips_b: '41940', name_a: "Enid, OK *", name_b: "San Jose, CA", state_a: 'OK', state_b: 'CA', rpp_a: 84.269, rpp_b: 110.423, ratio_a_to_b: 1.3104, ratio_b_to_a: 0.7631, gap_abs: 26.15 },
  // #87 gap 26.14
  { pair_slug: 'florence-muscle-shoals-al-vs-urban-honolulu-hi', slug_a: 'florence-muscle-shoals-al', slug_b: 'urban-honolulu-hi', fips_a: '22520', fips_b: '46520', name_a: "Florence, AL", name_b: "Urban Honolulu, HI", state_a: 'AL', state_b: 'HI', rpp_a: 84.817, rpp_b: 110.961, ratio_a_to_b: 1.3082, ratio_b_to_a: 0.7644, gap_abs: 26.14 },
  // #88 gap 26.09
  { pair_slug: 'eagle-pass-tx-vs-santa-cruz-watsonville-ca', slug_a: 'eagle-pass-tx', slug_b: 'santa-cruz-watsonville-ca', fips_a: '20580', fips_b: '42100', name_a: "Eagle Pass, TX", name_b: "Santa Cruz, CA", state_a: 'TX', state_b: 'CA', rpp_a: 83.805, rpp_b: 109.896, ratio_a_to_b: 1.3113, ratio_b_to_a: 0.7626, gap_abs: 26.09 },
  // #89 gap 26.07
  { pair_slug: 'hammond-la-vs-oxnard-thousand-oaks-ventura-ca', slug_a: 'hammond-la', slug_b: 'oxnard-thousand-oaks-ventura-ca', fips_a: '25220', fips_b: '37100', name_a: "Hammond, LA", name_b: "Oxnard, CA", state_a: 'LA', state_b: 'CA', rpp_a: 84.46, rpp_b: 110.534, ratio_a_to_b: 1.3087, ratio_b_to_a: 0.7641, gap_abs: 26.07 },
  // #90 gap 26.06
  { pair_slug: 'dothan-al-vs-santa-cruz-watsonville-ca', slug_a: 'dothan-al', slug_b: 'santa-cruz-watsonville-ca', fips_a: '20020', fips_b: '42100', name_a: "Dothan, AL", name_b: "Santa Cruz, CA", state_a: 'AL', state_b: 'CA', rpp_a: 83.833, rpp_b: 109.896, ratio_a_to_b: 1.3109, ratio_b_to_a: 0.7628, gap_abs: 26.06 },
  // #91 gap 26.03
  { pair_slug: 'houma-bayou-cane-thibodaux-la-vs-seattle-tacoma-bellevue-wa', slug_a: 'houma-bayou-cane-thibodaux-la', slug_b: 'seattle-tacoma-bellevue-wa', fips_a: '26380', fips_b: '42660', name_a: "Houma, LA", name_b: "Seattle, WA", state_a: 'LA', state_b: 'WA', rpp_a: 85.103, rpp_b: 111.133, ratio_a_to_b: 1.3059, ratio_b_to_a: 0.7658, gap_abs: 26.03 },
  // #92 gap 25.96
  { pair_slug: 'hammond-la-vs-san-jose-sunnyvale-santa-clara-ca', slug_a: 'hammond-la', slug_b: 'san-jose-sunnyvale-santa-clara-ca', fips_a: '25220', fips_b: '41940', name_a: "Hammond, LA", name_b: "San Jose, CA", state_a: 'LA', state_b: 'CA', rpp_a: 84.46, rpp_b: 110.423, ratio_a_to_b: 1.3074, ratio_b_to_a: 0.7649, gap_abs: 25.96 },
  // #93 gap 25.88
  { pair_slug: 'santa-cruz-watsonville-ca-vs-texarkana-tx-ar', slug_a: 'santa-cruz-watsonville-ca', slug_b: 'texarkana-tx-ar', fips_a: '42100', fips_b: '45500', name_a: "Santa Cruz, CA", name_b: "Texarkana, TX", state_a: 'CA', state_b: 'TX', rpp_a: 109.896, rpp_b: 84.012, ratio_a_to_b: 0.7645, ratio_b_to_a: 1.3081, gap_abs: 25.88 },
  // #94 gap 25.86
  { pair_slug: 'houma-bayou-cane-thibodaux-la-vs-urban-honolulu-hi', slug_a: 'houma-bayou-cane-thibodaux-la', slug_b: 'urban-honolulu-hi', fips_a: '26380', fips_b: '46520', name_a: "Houma, LA", name_b: "Urban Honolulu, HI", state_a: 'LA', state_b: 'HI', rpp_a: 85.103, rpp_b: 110.961, ratio_a_to_b: 1.3038, ratio_b_to_a: 0.767, gap_abs: 25.86 },
  // #95 gap 25.83
  { pair_slug: 'kiryas-joel-poughkeepsie-newburgh-ny-vs-monroe-la', slug_a: 'kiryas-joel-poughkeepsie-newburgh-ny', slug_b: 'monroe-la', fips_a: '28880', fips_b: '33740', name_a: "Kiryas Joel, NY", name_b: "Monroe, LA", state_a: 'NY', state_b: 'LA', rpp_a: 109.422, rpp_b: 83.597, ratio_a_to_b: 0.764, ratio_b_to_a: 1.3089, gap_abs: 25.83 },
  // #96 gap 25.80
  { pair_slug: 'kahului-wailuku-hi-vs-monroe-la', slug_a: 'kahului-wailuku-hi', slug_b: 'monroe-la', fips_a: '27980', fips_b: '33740', name_a: "Kahului, HI", name_b: "Monroe, LA", state_a: 'HI', state_b: 'LA', rpp_a: 109.393, rpp_b: 83.597, ratio_a_to_b: 0.7642, ratio_b_to_a: 1.3086, gap_abs: 25.8 },
  // #97 gap 25.77
  { pair_slug: 'oxnard-thousand-oaks-ventura-ca-vs-shreveport-bossier-city-la', slug_a: 'oxnard-thousand-oaks-ventura-ca', slug_b: 'shreveport-bossier-city-la', fips_a: '37100', fips_b: '43340', name_a: "Oxnard, CA", name_b: "Shreveport, LA", state_a: 'CA', state_b: 'LA', rpp_a: 110.534, rpp_b: 84.766, ratio_a_to_b: 0.7669, ratio_b_to_a: 1.304, gap_abs: 25.77 },
  // #98 gap 25.72
  { pair_slug: 'florence-muscle-shoals-al-vs-oxnard-thousand-oaks-ventura-ca', slug_a: 'florence-muscle-shoals-al', slug_b: 'oxnard-thousand-oaks-ventura-ca', fips_a: '22520', fips_b: '37100', name_a: "Florence, AL", name_b: "Oxnard, CA", state_a: 'AL', state_b: 'CA', rpp_a: 84.817, rpp_b: 110.534, ratio_a_to_b: 1.3032, ratio_b_to_a: 0.7673, gap_abs: 25.72 },
  // #99 gap 25.71
  { pair_slug: 'seattle-tacoma-bellevue-wa-vs-wildwood-the-villages-fl', slug_a: 'seattle-tacoma-bellevue-wa', slug_b: 'wildwood-the-villages-fl', fips_a: '42660', fips_b: '48680', name_a: "Seattle, WA", name_b: "Wildwood, FL", state_a: 'WA', state_b: 'FL', rpp_a: 111.133, rpp_b: 85.424, ratio_a_to_b: 0.7687, ratio_b_to_a: 1.301, gap_abs: 25.71 },
  // #100 gap 25.66
  { pair_slug: 'san-jose-sunnyvale-santa-clara-ca-vs-shreveport-bossier-city-la', slug_a: 'san-jose-sunnyvale-santa-clara-ca', slug_b: 'shreveport-bossier-city-la', fips_a: '41940', fips_b: '43340', name_a: "San Jose, CA", name_b: "Shreveport, LA", state_a: 'CA', state_b: 'LA', rpp_a: 110.423, rpp_b: 84.766, ratio_a_to_b: 0.7676, ratio_b_to_a: 1.3027, gap_abs: 25.66 },
  // #101 gap 25.63
  { pair_slug: 'enid-ok-vs-santa-cruz-watsonville-ca', slug_a: 'enid-ok', slug_b: 'santa-cruz-watsonville-ca', fips_a: '21420', fips_b: '42100', name_a: "Enid, OK *", name_b: "Santa Cruz, CA", state_a: 'OK', state_b: 'CA', rpp_a: 84.269, rpp_b: 109.896, ratio_a_to_b: 1.3041, ratio_b_to_a: 0.7668, gap_abs: 25.63 },
  // #102 gap 25.62
  { pair_slug: 'eagle-pass-tx-vs-kiryas-joel-poughkeepsie-newburgh-ny', slug_a: 'eagle-pass-tx', slug_b: 'kiryas-joel-poughkeepsie-newburgh-ny', fips_a: '20580', fips_b: '28880', name_a: "Eagle Pass, TX", name_b: "Kiryas Joel, NY", state_a: 'TX', state_b: 'NY', rpp_a: 83.805, rpp_b: 109.422, ratio_a_to_b: 1.3057, ratio_b_to_a: 0.7659, gap_abs: 25.62 },
  // #103 gap 25.61
  { pair_slug: 'florence-muscle-shoals-al-vs-san-jose-sunnyvale-santa-clara-ca', slug_a: 'florence-muscle-shoals-al', slug_b: 'san-jose-sunnyvale-santa-clara-ca', fips_a: '22520', fips_b: '41940', name_a: "Florence, AL", name_b: "San Jose, CA", state_a: 'AL', state_b: 'CA', rpp_a: 84.817, rpp_b: 110.423, ratio_a_to_b: 1.3019, ratio_b_to_a: 0.7681, gap_abs: 25.61 },
  // #104 gap 25.59
  { pair_slug: 'dothan-al-vs-kiryas-joel-poughkeepsie-newburgh-ny', slug_a: 'dothan-al', slug_b: 'kiryas-joel-poughkeepsie-newburgh-ny', fips_a: '20020', fips_b: '28880', name_a: "Dothan, AL", name_b: "Kiryas Joel, NY", state_a: 'AL', state_b: 'NY', rpp_a: 83.833, rpp_b: 109.422, ratio_a_to_b: 1.3052, ratio_b_to_a: 0.7661, gap_abs: 25.59 },
  // #105 gap 25.59
  { pair_slug: 'eagle-pass-tx-vs-kahului-wailuku-hi', slug_a: 'eagle-pass-tx', slug_b: 'kahului-wailuku-hi', fips_a: '20580', fips_b: '27980', name_a: "Eagle Pass, TX", name_b: "Kahului, HI", state_a: 'TX', state_b: 'HI', rpp_a: 83.805, rpp_b: 109.393, ratio_a_to_b: 1.3053, ratio_b_to_a: 0.7661, gap_abs: 25.59 },
  // #106 gap 25.56
  { pair_slug: 'dothan-al-vs-kahului-wailuku-hi', slug_a: 'dothan-al', slug_b: 'kahului-wailuku-hi', fips_a: '20020', fips_b: '27980', name_a: "Dothan, AL", name_b: "Kahului, HI", state_a: 'AL', state_b: 'HI', rpp_a: 83.833, rpp_b: 109.393, ratio_a_to_b: 1.3049, ratio_b_to_a: 0.7663, gap_abs: 25.56 },
  // #107 gap 25.54
  { pair_slug: 'urban-honolulu-hi-vs-wildwood-the-villages-fl', slug_a: 'urban-honolulu-hi', slug_b: 'wildwood-the-villages-fl', fips_a: '46520', fips_b: '48680', name_a: "Urban Honolulu, HI", name_b: "Wildwood, FL", state_a: 'HI', state_b: 'FL', rpp_a: 110.961, rpp_b: 85.424, ratio_a_to_b: 0.7699, ratio_b_to_a: 1.2989, gap_abs: 25.54 },
  // #108 gap 25.45
  { pair_slug: 'monroe-la-vs-salinas-ca', slug_a: 'monroe-la', slug_b: 'salinas-ca', fips_a: '33740', fips_b: '41500', name_a: "Monroe, LA", name_b: "Salinas, CA", state_a: 'LA', state_b: 'CA', rpp_a: 83.597, rpp_b: 109.042, ratio_a_to_b: 1.3044, ratio_b_to_a: 0.7666, gap_abs: 25.45 },
  // #109 gap 25.44
  { pair_slug: 'hammond-la-vs-santa-cruz-watsonville-ca', slug_a: 'hammond-la', slug_b: 'santa-cruz-watsonville-ca', fips_a: '25220', fips_b: '42100', name_a: "Hammond, LA", name_b: "Santa Cruz, CA", state_a: 'LA', state_b: 'CA', rpp_a: 84.46, rpp_b: 109.896, ratio_a_to_b: 1.3012, ratio_b_to_a: 0.7685, gap_abs: 25.44 },
  // #110 gap 25.43
  { pair_slug: 'houma-bayou-cane-thibodaux-la-vs-oxnard-thousand-oaks-ventura-ca', slug_a: 'houma-bayou-cane-thibodaux-la', slug_b: 'oxnard-thousand-oaks-ventura-ca', fips_a: '26380', fips_b: '37100', name_a: "Houma, LA", name_b: "Oxnard, CA", state_a: 'LA', state_b: 'CA', rpp_a: 85.103, rpp_b: 110.534, ratio_a_to_b: 1.2988, ratio_b_to_a: 0.7699, gap_abs: 25.43 },
  // #111 gap 25.41
  { pair_slug: 'kiryas-joel-poughkeepsie-newburgh-ny-vs-texarkana-tx-ar', slug_a: 'kiryas-joel-poughkeepsie-newburgh-ny', slug_b: 'texarkana-tx-ar', fips_a: '28880', fips_b: '45500', name_a: "Kiryas Joel, NY", name_b: "Texarkana, TX", state_a: 'NY', state_b: 'TX', rpp_a: 109.422, rpp_b: 84.012, ratio_a_to_b: 0.7678, ratio_b_to_a: 1.3025, gap_abs: 25.41 },
  // #112 gap 25.38
  { pair_slug: 'kahului-wailuku-hi-vs-texarkana-tx-ar', slug_a: 'kahului-wailuku-hi', slug_b: 'texarkana-tx-ar', fips_a: '27980', fips_b: '45500', name_a: "Kahului, HI", name_b: "Texarkana, TX", state_a: 'HI', state_b: 'TX', rpp_a: 109.393, rpp_b: 84.012, ratio_a_to_b: 0.768, ratio_b_to_a: 1.3021, gap_abs: 25.38 },
  // #113 gap 25.32
  { pair_slug: 'houma-bayou-cane-thibodaux-la-vs-san-jose-sunnyvale-santa-clara-ca', slug_a: 'houma-bayou-cane-thibodaux-la', slug_b: 'san-jose-sunnyvale-santa-clara-ca', fips_a: '26380', fips_b: '41940', name_a: "Houma, LA", name_b: "San Jose, CA", state_a: 'LA', state_b: 'CA', rpp_a: 85.103, rpp_b: 110.423, ratio_a_to_b: 1.2975, ratio_b_to_a: 0.7707, gap_abs: 25.32 },
  // #114 gap 25.29
  { pair_slug: 'monroe-la-vs-washington-arlington-alexandria-dc-va-md-wv', slug_a: 'monroe-la', slug_b: 'washington-arlington-alexandria-dc-va-md-wv', fips_a: '33740', fips_b: '47900', name_a: "Monroe, LA", name_b: "Washington, DC", state_a: 'LA', state_b: 'DC', rpp_a: 83.597, rpp_b: 108.884, ratio_a_to_b: 1.3025, ratio_b_to_a: 0.7678, gap_abs: 25.29 },
  // #115 gap 25.24
  { pair_slug: 'eagle-pass-tx-vs-salinas-ca', slug_a: 'eagle-pass-tx', slug_b: 'salinas-ca', fips_a: '20580', fips_b: '41500', name_a: "Eagle Pass, TX", name_b: "Salinas, CA", state_a: 'TX', state_b: 'CA', rpp_a: 83.805, rpp_b: 109.042, ratio_a_to_b: 1.3011, ratio_b_to_a: 0.7686, gap_abs: 25.24 },
  // #116 gap 25.21
  { pair_slug: 'dothan-al-vs-salinas-ca', slug_a: 'dothan-al', slug_b: 'salinas-ca', fips_a: '20020', fips_b: '41500', name_a: "Dothan, AL", name_b: "Salinas, CA", state_a: 'AL', state_b: 'CA', rpp_a: 83.833, rpp_b: 109.042, ratio_a_to_b: 1.3007, ratio_b_to_a: 0.7688, gap_abs: 25.21 },
  // #117 gap 25.20
  { pair_slug: 'monroe-la-vs-santa-maria-santa-barbara-ca', slug_a: 'monroe-la', slug_b: 'santa-maria-santa-barbara-ca', fips_a: '33740', fips_b: '42200', name_a: "Monroe, LA", name_b: "Santa Maria, CA", state_a: 'LA', state_b: 'CA', rpp_a: 83.597, rpp_b: 108.798, ratio_a_to_b: 1.3015, ratio_b_to_a: 0.7684, gap_abs: 25.2 },
  // #118 gap 25.15
  { pair_slug: 'enid-ok-vs-kiryas-joel-poughkeepsie-newburgh-ny', slug_a: 'enid-ok', slug_b: 'kiryas-joel-poughkeepsie-newburgh-ny', fips_a: '21420', fips_b: '28880', name_a: "Enid, OK *", name_b: "Kiryas Joel, NY", state_a: 'OK', state_b: 'NY', rpp_a: 84.269, rpp_b: 109.422, ratio_a_to_b: 1.2985, ratio_b_to_a: 0.7701, gap_abs: 25.15 },
  // #119 gap 25.13
  { pair_slug: 'santa-cruz-watsonville-ca-vs-shreveport-bossier-city-la', slug_a: 'santa-cruz-watsonville-ca', slug_b: 'shreveport-bossier-city-la', fips_a: '42100', fips_b: '43340', name_a: "Santa Cruz, CA", name_b: "Shreveport, LA", state_a: 'CA', state_b: 'LA', rpp_a: 109.896, rpp_b: 84.766, ratio_a_to_b: 0.7713, ratio_b_to_a: 1.2965, gap_abs: 25.13 },
  // #120 gap 25.12
  { pair_slug: 'enid-ok-vs-kahului-wailuku-hi', slug_a: 'enid-ok', slug_b: 'kahului-wailuku-hi', fips_a: '21420', fips_b: '27980', name_a: "Enid, OK *", name_b: "Kahului, HI", state_a: 'OK', state_b: 'HI', rpp_a: 84.269, rpp_b: 109.393, ratio_a_to_b: 1.2981, ratio_b_to_a: 0.7703, gap_abs: 25.12 },
  // #121 gap 25.11
  { pair_slug: 'oxnard-thousand-oaks-ventura-ca-vs-wildwood-the-villages-fl', slug_a: 'oxnard-thousand-oaks-ventura-ca', slug_b: 'wildwood-the-villages-fl', fips_a: '37100', fips_b: '48680', name_a: "Oxnard, CA", name_b: "Wildwood, FL", state_a: 'CA', state_b: 'FL', rpp_a: 110.534, rpp_b: 85.424, ratio_a_to_b: 0.7728, ratio_b_to_a: 1.2939, gap_abs: 25.11 },
  // #122 gap 25.08
  { pair_slug: 'florence-muscle-shoals-al-vs-santa-cruz-watsonville-ca', slug_a: 'florence-muscle-shoals-al', slug_b: 'santa-cruz-watsonville-ca', fips_a: '22520', fips_b: '42100', name_a: "Florence, AL", name_b: "Santa Cruz, CA", state_a: 'AL', state_b: 'CA', rpp_a: 84.817, rpp_b: 109.896, ratio_a_to_b: 1.2957, ratio_b_to_a: 0.7718, gap_abs: 25.08 },
  // #123 gap 25.08
  { pair_slug: 'eagle-pass-tx-vs-washington-arlington-alexandria-dc-va-md-wv', slug_a: 'eagle-pass-tx', slug_b: 'washington-arlington-alexandria-dc-va-md-wv', fips_a: '20580', fips_b: '47900', name_a: "Eagle Pass, TX", name_b: "Washington, DC", state_a: 'TX', state_b: 'DC', rpp_a: 83.805, rpp_b: 108.884, ratio_a_to_b: 1.2993, ratio_b_to_a: 0.7697, gap_abs: 25.08 },
  // #124 gap 25.05
  { pair_slug: 'dothan-al-vs-washington-arlington-alexandria-dc-va-md-wv', slug_a: 'dothan-al', slug_b: 'washington-arlington-alexandria-dc-va-md-wv', fips_a: '20020', fips_b: '47900', name_a: "Dothan, AL", name_b: "Washington, DC", state_a: 'AL', state_b: 'DC', rpp_a: 83.833, rpp_b: 108.884, ratio_a_to_b: 1.2988, ratio_b_to_a: 0.7699, gap_abs: 25.05 },
  // #125 gap 25.03
  { pair_slug: 'salinas-ca-vs-texarkana-tx-ar', slug_a: 'salinas-ca', slug_b: 'texarkana-tx-ar', fips_a: '41500', fips_b: '45500', name_a: "Salinas, CA", name_b: "Texarkana, TX", state_a: 'CA', state_b: 'TX', rpp_a: 109.042, rpp_b: 84.012, ratio_a_to_b: 0.7705, ratio_b_to_a: 1.2979, gap_abs: 25.03 },
  // #126 gap 25.00
  { pair_slug: 'monroe-la-vs-san-luis-obispo-paso-robles-ca', slug_a: 'monroe-la', slug_b: 'san-luis-obispo-paso-robles-ca', fips_a: '33740', fips_b: '42020', name_a: "Monroe, LA", name_b: "San Luis Obispo, CA", state_a: 'LA', state_b: 'CA', rpp_a: 83.597, rpp_b: 108.596, ratio_a_to_b: 1.299, ratio_b_to_a: 0.7698, gap_abs: 25 },
  // #127 gap 25.00
  { pair_slug: 'san-jose-sunnyvale-santa-clara-ca-vs-wildwood-the-villages-fl', slug_a: 'san-jose-sunnyvale-santa-clara-ca', slug_b: 'wildwood-the-villages-fl', fips_a: '41940', fips_b: '48680', name_a: "San Jose, CA", name_b: "Wildwood, FL", state_a: 'CA', state_b: 'FL', rpp_a: 110.423, rpp_b: 85.424, ratio_a_to_b: 0.7736, ratio_b_to_a: 1.2926, gap_abs: 25 },
  // #128 gap 24.99
  { pair_slug: 'eagle-pass-tx-vs-santa-maria-santa-barbara-ca', slug_a: 'eagle-pass-tx', slug_b: 'santa-maria-santa-barbara-ca', fips_a: '20580', fips_b: '42200', name_a: "Eagle Pass, TX", name_b: "Santa Maria, CA", state_a: 'TX', state_b: 'CA', rpp_a: 83.805, rpp_b: 108.798, ratio_a_to_b: 1.2982, ratio_b_to_a: 0.7703, gap_abs: 24.99 },
  // #129 gap 24.97
  { pair_slug: 'dothan-al-vs-santa-maria-santa-barbara-ca', slug_a: 'dothan-al', slug_b: 'santa-maria-santa-barbara-ca', fips_a: '20020', fips_b: '42200', name_a: "Dothan, AL", name_b: "Santa Maria, CA", state_a: 'AL', state_b: 'CA', rpp_a: 83.833, rpp_b: 108.798, ratio_a_to_b: 1.2978, ratio_b_to_a: 0.7705, gap_abs: 24.97 },
  // #130 gap 24.96
  { pair_slug: 'hammond-la-vs-kiryas-joel-poughkeepsie-newburgh-ny', slug_a: 'hammond-la', slug_b: 'kiryas-joel-poughkeepsie-newburgh-ny', fips_a: '25220', fips_b: '28880', name_a: "Hammond, LA", name_b: "Kiryas Joel, NY", state_a: 'LA', state_b: 'NY', rpp_a: 84.46, rpp_b: 109.422, ratio_a_to_b: 1.2955, ratio_b_to_a: 0.7719, gap_abs: 24.96 },
  // #131 gap 24.93
  { pair_slug: 'hammond-la-vs-kahului-wailuku-hi', slug_a: 'hammond-la', slug_b: 'kahului-wailuku-hi', fips_a: '25220', fips_b: '27980', name_a: "Hammond, LA", name_b: "Kahului, HI", state_a: 'LA', state_b: 'HI', rpp_a: 84.46, rpp_b: 109.393, ratio_a_to_b: 1.2952, ratio_b_to_a: 0.7721, gap_abs: 24.93 },
  // #132 gap 24.88
  { pair_slug: 'monroe-la-vs-vallejo-ca', slug_a: 'monroe-la', slug_b: 'vallejo-ca', fips_a: '33740', fips_b: '46700', name_a: "Monroe, LA", name_b: "Vallejo, CA", state_a: 'LA', state_b: 'CA', rpp_a: 83.597, rpp_b: 108.479, ratio_a_to_b: 1.2976, ratio_b_to_a: 0.7706, gap_abs: 24.88 },
  // #133 gap 24.87
  { pair_slug: 'texarkana-tx-ar-vs-washington-arlington-alexandria-dc-va-md-wv', slug_a: 'texarkana-tx-ar', slug_b: 'washington-arlington-alexandria-dc-va-md-wv', fips_a: '45500', fips_b: '47900', name_a: "Texarkana, TX", name_b: "Washington, DC", state_a: 'TX', state_b: 'DC', rpp_a: 84.012, rpp_b: 108.884, ratio_a_to_b: 1.2961, ratio_b_to_a: 0.7716, gap_abs: 24.87 },
  // #134 gap 24.79
  { pair_slug: 'houma-bayou-cane-thibodaux-la-vs-santa-cruz-watsonville-ca', slug_a: 'houma-bayou-cane-thibodaux-la', slug_b: 'santa-cruz-watsonville-ca', fips_a: '26380', fips_b: '42100', name_a: "Houma, LA", name_b: "Santa Cruz, CA", state_a: 'LA', state_b: 'CA', rpp_a: 85.103, rpp_b: 109.896, ratio_a_to_b: 1.2913, ratio_b_to_a: 0.7744, gap_abs: 24.79 },
  // #135 gap 24.79
  { pair_slug: 'eagle-pass-tx-vs-san-luis-obispo-paso-robles-ca', slug_a: 'eagle-pass-tx', slug_b: 'san-luis-obispo-paso-robles-ca', fips_a: '20580', fips_b: '42020', name_a: "Eagle Pass, TX", name_b: "San Luis Obispo, CA", state_a: 'TX', state_b: 'CA', rpp_a: 83.805, rpp_b: 108.596, ratio_a_to_b: 1.2958, ratio_b_to_a: 0.7717, gap_abs: 24.79 },
  // #136 gap 24.79
  { pair_slug: 'santa-maria-santa-barbara-ca-vs-texarkana-tx-ar', slug_a: 'santa-maria-santa-barbara-ca', slug_b: 'texarkana-tx-ar', fips_a: '42200', fips_b: '45500', name_a: "Santa Maria, CA", name_b: "Texarkana, TX", state_a: 'CA', state_b: 'TX', rpp_a: 108.798, rpp_b: 84.012, ratio_a_to_b: 0.7722, ratio_b_to_a: 1.295, gap_abs: 24.79 },
  // #137 gap 24.77
  { pair_slug: 'enid-ok-vs-salinas-ca', slug_a: 'enid-ok', slug_b: 'salinas-ca', fips_a: '21420', fips_b: '41500', name_a: "Enid, OK *", name_b: "Salinas, CA", state_a: 'OK', state_b: 'CA', rpp_a: 84.269, rpp_b: 109.042, ratio_a_to_b: 1.294, ratio_b_to_a: 0.7728, gap_abs: 24.77 },
  // #138 gap 24.76
  { pair_slug: 'dothan-al-vs-san-luis-obispo-paso-robles-ca', slug_a: 'dothan-al', slug_b: 'san-luis-obispo-paso-robles-ca', fips_a: '20020', fips_b: '42020', name_a: "Dothan, AL", name_b: "San Luis Obispo, CA", state_a: 'AL', state_b: 'CA', rpp_a: 83.833, rpp_b: 108.596, ratio_a_to_b: 1.2954, ratio_b_to_a: 0.772, gap_abs: 24.76 },
  // #139 gap 24.67
  { pair_slug: 'eagle-pass-tx-vs-vallejo-ca', slug_a: 'eagle-pass-tx', slug_b: 'vallejo-ca', fips_a: '20580', fips_b: '46700', name_a: "Eagle Pass, TX", name_b: "Vallejo, CA", state_a: 'TX', state_b: 'CA', rpp_a: 83.805, rpp_b: 108.479, ratio_a_to_b: 1.2944, ratio_b_to_a: 0.7725, gap_abs: 24.67 },
  // #140 gap 24.67
  { pair_slug: 'boston-cambridge-newton-ma-nh-vs-monroe-la', slug_a: 'boston-cambridge-newton-ma-nh', slug_b: 'monroe-la', fips_a: '14460', fips_b: '33740', name_a: "Boston, MA", name_b: "Monroe, LA", state_a: 'MA', state_b: 'LA', rpp_a: 108.266, rpp_b: 83.597, ratio_a_to_b: 0.7721, ratio_b_to_a: 1.2951, gap_abs: 24.67 },
  // #141 gap 24.66
  { pair_slug: 'kiryas-joel-poughkeepsie-newburgh-ny-vs-shreveport-bossier-city-la', slug_a: 'kiryas-joel-poughkeepsie-newburgh-ny', slug_b: 'shreveport-bossier-city-la', fips_a: '28880', fips_b: '43340', name_a: "Kiryas Joel, NY", name_b: "Shreveport, LA", state_a: 'NY', state_b: 'LA', rpp_a: 109.422, rpp_b: 84.766, ratio_a_to_b: 0.7747, ratio_b_to_a: 1.2909, gap_abs: 24.66 },
  // #142 gap 24.65
  { pair_slug: 'dothan-al-vs-vallejo-ca', slug_a: 'dothan-al', slug_b: 'vallejo-ca', fips_a: '20020', fips_b: '46700', name_a: "Dothan, AL", name_b: "Vallejo, CA", state_a: 'AL', state_b: 'CA', rpp_a: 83.833, rpp_b: 108.479, ratio_a_to_b: 1.294, ratio_b_to_a: 0.7728, gap_abs: 24.65 },
  // #143 gap 24.63
  { pair_slug: 'kahului-wailuku-hi-vs-shreveport-bossier-city-la', slug_a: 'kahului-wailuku-hi', slug_b: 'shreveport-bossier-city-la', fips_a: '27980', fips_b: '43340', name_a: "Kahului, HI", name_b: "Shreveport, LA", state_a: 'HI', state_b: 'LA', rpp_a: 109.393, rpp_b: 84.766, ratio_a_to_b: 0.7749, ratio_b_to_a: 1.2905, gap_abs: 24.63 },
  // #144 gap 24.61
  { pair_slug: 'enid-ok-vs-washington-arlington-alexandria-dc-va-md-wv', slug_a: 'enid-ok', slug_b: 'washington-arlington-alexandria-dc-va-md-wv', fips_a: '21420', fips_b: '47900', name_a: "Enid, OK *", name_b: "Washington, DC", state_a: 'OK', state_b: 'DC', rpp_a: 84.269, rpp_b: 108.884, ratio_a_to_b: 1.2921, ratio_b_to_a: 0.7739, gap_abs: 24.61 },
  // #145 gap 24.61
  { pair_slug: 'florence-muscle-shoals-al-vs-kiryas-joel-poughkeepsie-newburgh-ny', slug_a: 'florence-muscle-shoals-al', slug_b: 'kiryas-joel-poughkeepsie-newburgh-ny', fips_a: '22520', fips_b: '28880', name_a: "Florence, AL", name_b: "Kiryas Joel, NY", state_a: 'AL', state_b: 'NY', rpp_a: 84.817, rpp_b: 109.422, ratio_a_to_b: 1.2901, ratio_b_to_a: 0.7751, gap_abs: 24.61 },
  // #146 gap 24.58
  { pair_slug: 'san-luis-obispo-paso-robles-ca-vs-texarkana-tx-ar', slug_a: 'san-luis-obispo-paso-robles-ca', slug_b: 'texarkana-tx-ar', fips_a: '42020', fips_b: '45500', name_a: "San Luis Obispo, CA", name_b: "Texarkana, TX", state_a: 'CA', state_b: 'TX', rpp_a: 108.596, rpp_b: 84.012, ratio_a_to_b: 0.7736, ratio_b_to_a: 1.2926, gap_abs: 24.58 },
  // #147 gap 24.58
  { pair_slug: 'hammond-la-vs-salinas-ca', slug_a: 'hammond-la', slug_b: 'salinas-ca', fips_a: '25220', fips_b: '41500', name_a: "Hammond, LA", name_b: "Salinas, CA", state_a: 'LA', state_b: 'CA', rpp_a: 84.46, rpp_b: 109.042, ratio_a_to_b: 1.291, ratio_b_to_a: 0.7746, gap_abs: 24.58 },
  // #148 gap 24.58
  { pair_slug: 'florence-muscle-shoals-al-vs-kahului-wailuku-hi', slug_a: 'florence-muscle-shoals-al', slug_b: 'kahului-wailuku-hi', fips_a: '22520', fips_b: '27980', name_a: "Florence, AL", name_b: "Kahului, HI", state_a: 'AL', state_b: 'HI', rpp_a: 84.817, rpp_b: 109.393, ratio_a_to_b: 1.2898, ratio_b_to_a: 0.7753, gap_abs: 24.58 },
  // #149 gap 24.53
  { pair_slug: 'enid-ok-vs-santa-maria-santa-barbara-ca', slug_a: 'enid-ok', slug_b: 'santa-maria-santa-barbara-ca', fips_a: '21420', fips_b: '42200', name_a: "Enid, OK *", name_b: "Santa Maria, CA", state_a: 'OK', state_b: 'CA', rpp_a: 84.269, rpp_b: 108.798, ratio_a_to_b: 1.2911, ratio_b_to_a: 0.7745, gap_abs: 24.53 },
  // #150 gap 24.47
  { pair_slug: 'santa-cruz-watsonville-ca-vs-wildwood-the-villages-fl', slug_a: 'santa-cruz-watsonville-ca', slug_b: 'wildwood-the-villages-fl', fips_a: '42100', fips_b: '48680', name_a: "Santa Cruz, CA", name_b: "Wildwood, FL", state_a: 'CA', state_b: 'FL', rpp_a: 109.896, rpp_b: 85.424, ratio_a_to_b: 0.7773, ratio_b_to_a: 1.2865, gap_abs: 24.47 },
  // #151 gap 24.47
  { pair_slug: 'texarkana-tx-ar-vs-vallejo-ca', slug_a: 'texarkana-tx-ar', slug_b: 'vallejo-ca', fips_a: '45500', fips_b: '46700', name_a: "Texarkana, TX", name_b: "Vallejo, CA", state_a: 'TX', state_b: 'CA', rpp_a: 84.012, rpp_b: 108.479, ratio_a_to_b: 1.2912, ratio_b_to_a: 0.7745, gap_abs: 24.47 },
  // #152 gap 24.46
  { pair_slug: 'boston-cambridge-newton-ma-nh-vs-eagle-pass-tx', slug_a: 'boston-cambridge-newton-ma-nh', slug_b: 'eagle-pass-tx', fips_a: '14460', fips_b: '20580', name_a: "Boston, MA", name_b: "Eagle Pass, TX", state_a: 'MA', state_b: 'TX', rpp_a: 108.266, rpp_b: 83.805, ratio_a_to_b: 0.7741, ratio_b_to_a: 1.2919, gap_abs: 24.46 },
  // #153 gap 24.43
  { pair_slug: 'boston-cambridge-newton-ma-nh-vs-dothan-al', slug_a: 'boston-cambridge-newton-ma-nh', slug_b: 'dothan-al', fips_a: '14460', fips_b: '20020', name_a: "Boston, MA", name_b: "Dothan, AL", state_a: 'MA', state_b: 'AL', rpp_a: 108.266, rpp_b: 83.833, ratio_a_to_b: 0.7743, ratio_b_to_a: 1.2914, gap_abs: 24.43 },
  // #154 gap 24.42
  { pair_slug: 'hammond-la-vs-washington-arlington-alexandria-dc-va-md-wv', slug_a: 'hammond-la', slug_b: 'washington-arlington-alexandria-dc-va-md-wv', fips_a: '25220', fips_b: '47900', name_a: "Hammond, LA", name_b: "Washington, DC", state_a: 'LA', state_b: 'DC', rpp_a: 84.46, rpp_b: 108.884, ratio_a_to_b: 1.2892, ratio_b_to_a: 0.7757, gap_abs: 24.42 },
  // #155 gap 24.34
  { pair_slug: 'hammond-la-vs-santa-maria-santa-barbara-ca', slug_a: 'hammond-la', slug_b: 'santa-maria-santa-barbara-ca', fips_a: '25220', fips_b: '42200', name_a: "Hammond, LA", name_b: "Santa Maria, CA", state_a: 'LA', state_b: 'CA', rpp_a: 84.46, rpp_b: 108.798, ratio_a_to_b: 1.2882, ratio_b_to_a: 0.7763, gap_abs: 24.34 },
  // #156 gap 24.33
  { pair_slug: 'enid-ok-vs-san-luis-obispo-paso-robles-ca', slug_a: 'enid-ok', slug_b: 'san-luis-obispo-paso-robles-ca', fips_a: '21420', fips_b: '42020', name_a: "Enid, OK *", name_b: "San Luis Obispo, CA", state_a: 'OK', state_b: 'CA', rpp_a: 84.269, rpp_b: 108.596, ratio_a_to_b: 1.2887, ratio_b_to_a: 0.776, gap_abs: 24.33 },
  // #157 gap 24.32
  { pair_slug: 'houma-bayou-cane-thibodaux-la-vs-kiryas-joel-poughkeepsie-newburgh-ny', slug_a: 'houma-bayou-cane-thibodaux-la', slug_b: 'kiryas-joel-poughkeepsie-newburgh-ny', fips_a: '26380', fips_b: '28880', name_a: "Houma, LA", name_b: "Kiryas Joel, NY", state_a: 'LA', state_b: 'NY', rpp_a: 85.103, rpp_b: 109.422, ratio_a_to_b: 1.2858, ratio_b_to_a: 0.7778, gap_abs: 24.32 },
  // #158 gap 24.29
  { pair_slug: 'houma-bayou-cane-thibodaux-la-vs-kahului-wailuku-hi', slug_a: 'houma-bayou-cane-thibodaux-la', slug_b: 'kahului-wailuku-hi', fips_a: '26380', fips_b: '27980', name_a: "Houma, LA", name_b: "Kahului, HI", state_a: 'LA', state_b: 'HI', rpp_a: 85.103, rpp_b: 109.393, ratio_a_to_b: 1.2854, ratio_b_to_a: 0.778, gap_abs: 24.29 },
  // #159 gap 24.28
  { pair_slug: 'salinas-ca-vs-shreveport-bossier-city-la', slug_a: 'salinas-ca', slug_b: 'shreveport-bossier-city-la', fips_a: '41500', fips_b: '43340', name_a: "Salinas, CA", name_b: "Shreveport, LA", state_a: 'CA', state_b: 'LA', rpp_a: 109.042, rpp_b: 84.766, ratio_a_to_b: 0.7774, ratio_b_to_a: 1.2864, gap_abs: 24.28 },
  // #160 gap 24.25
  { pair_slug: 'boston-cambridge-newton-ma-nh-vs-texarkana-tx-ar', slug_a: 'boston-cambridge-newton-ma-nh', slug_b: 'texarkana-tx-ar', fips_a: '14460', fips_b: '45500', name_a: "Boston, MA", name_b: "Texarkana, TX", state_a: 'MA', state_b: 'TX', rpp_a: 108.266, rpp_b: 84.012, ratio_a_to_b: 0.776, ratio_b_to_a: 1.2887, gap_abs: 24.25 },
  // #161 gap 24.23
  { pair_slug: 'florence-muscle-shoals-al-vs-salinas-ca', slug_a: 'florence-muscle-shoals-al', slug_b: 'salinas-ca', fips_a: '22520', fips_b: '41500', name_a: "Florence, AL", name_b: "Salinas, CA", state_a: 'AL', state_b: 'CA', rpp_a: 84.817, rpp_b: 109.042, ratio_a_to_b: 1.2856, ratio_b_to_a: 0.7778, gap_abs: 24.23 },
  // #162 gap 24.21
  { pair_slug: 'enid-ok-vs-vallejo-ca', slug_a: 'enid-ok', slug_b: 'vallejo-ca', fips_a: '21420', fips_b: '46700', name_a: "Enid, OK *", name_b: "Vallejo, CA", state_a: 'OK', state_b: 'CA', rpp_a: 84.269, rpp_b: 108.479, ratio_a_to_b: 1.2873, ratio_b_to_a: 0.7768, gap_abs: 24.21 },
  // #163 gap 24.19
  { pair_slug: 'monroe-la-vs-santa-rosa-petaluma-ca', slug_a: 'monroe-la', slug_b: 'santa-rosa-petaluma-ca', fips_a: '33740', fips_b: '42220', name_a: "Monroe, LA", name_b: "Santa Rosa, CA", state_a: 'LA', state_b: 'CA', rpp_a: 83.597, rpp_b: 107.784, ratio_a_to_b: 1.2893, ratio_b_to_a: 0.7756, gap_abs: 24.19 },
  // #164 gap 24.14
  { pair_slug: 'hammond-la-vs-san-luis-obispo-paso-robles-ca', slug_a: 'hammond-la', slug_b: 'san-luis-obispo-paso-robles-ca', fips_a: '25220', fips_b: '42020', name_a: "Hammond, LA", name_b: "San Luis Obispo, CA", state_a: 'LA', state_b: 'CA', rpp_a: 84.46, rpp_b: 108.596, ratio_a_to_b: 1.2858, ratio_b_to_a: 0.7777, gap_abs: 24.14 },
  // #165 gap 24.12
  { pair_slug: 'shreveport-bossier-city-la-vs-washington-arlington-alexandria-dc-va-md-wv', slug_a: 'shreveport-bossier-city-la', slug_b: 'washington-arlington-alexandria-dc-va-md-wv', fips_a: '43340', fips_b: '47900', name_a: "Shreveport, LA", name_b: "Washington, DC", state_a: 'LA', state_b: 'DC', rpp_a: 84.766, rpp_b: 108.884, ratio_a_to_b: 1.2845, ratio_b_to_a: 0.7785, gap_abs: 24.12 },
  // #166 gap 24.07
  { pair_slug: 'florence-muscle-shoals-al-vs-washington-arlington-alexandria-dc-va-md-wv', slug_a: 'florence-muscle-shoals-al', slug_b: 'washington-arlington-alexandria-dc-va-md-wv', fips_a: '22520', fips_b: '47900', name_a: "Florence, AL", name_b: "Washington, DC", state_a: 'AL', state_b: 'DC', rpp_a: 84.817, rpp_b: 108.884, ratio_a_to_b: 1.2838, ratio_b_to_a: 0.779, gap_abs: 24.07 },
  // #167 gap 24.03
  { pair_slug: 'santa-maria-santa-barbara-ca-vs-shreveport-bossier-city-la', slug_a: 'santa-maria-santa-barbara-ca', slug_b: 'shreveport-bossier-city-la', fips_a: '42200', fips_b: '43340', name_a: "Santa Maria, CA", name_b: "Shreveport, LA", state_a: 'CA', state_b: 'LA', rpp_a: 108.798, rpp_b: 84.766, ratio_a_to_b: 0.7791, ratio_b_to_a: 1.2835, gap_abs: 24.03 },
  // #168 gap 24.02
  { pair_slug: 'hammond-la-vs-vallejo-ca', slug_a: 'hammond-la', slug_b: 'vallejo-ca', fips_a: '25220', fips_b: '46700', name_a: "Hammond, LA", name_b: "Vallejo, CA", state_a: 'LA', state_b: 'CA', rpp_a: 84.46, rpp_b: 108.479, ratio_a_to_b: 1.2844, ratio_b_to_a: 0.7786, gap_abs: 24.02 },
  // #169 gap 24.00
  { pair_slug: 'kiryas-joel-poughkeepsie-newburgh-ny-vs-wildwood-the-villages-fl', slug_a: 'kiryas-joel-poughkeepsie-newburgh-ny', slug_b: 'wildwood-the-villages-fl', fips_a: '28880', fips_b: '48680', name_a: "Kiryas Joel, NY", name_b: "Wildwood, FL", state_a: 'NY', state_b: 'FL', rpp_a: 109.422, rpp_b: 85.424, ratio_a_to_b: 0.7807, ratio_b_to_a: 1.2809, gap_abs: 24 },
  // #170 gap 24.00
  { pair_slug: 'boston-cambridge-newton-ma-nh-vs-enid-ok', slug_a: 'boston-cambridge-newton-ma-nh', slug_b: 'enid-ok', fips_a: '14460', fips_b: '21420', name_a: "Boston, MA", name_b: "Enid, OK *", state_a: 'MA', state_b: 'OK', rpp_a: 108.266, rpp_b: 84.269, ratio_a_to_b: 0.7784, ratio_b_to_a: 1.2848, gap_abs: 24 },
  // #171 gap 23.98
  { pair_slug: 'florence-muscle-shoals-al-vs-santa-maria-santa-barbara-ca', slug_a: 'florence-muscle-shoals-al', slug_b: 'santa-maria-santa-barbara-ca', fips_a: '22520', fips_b: '42200', name_a: "Florence, AL", name_b: "Santa Maria, CA", state_a: 'AL', state_b: 'CA', rpp_a: 84.817, rpp_b: 108.798, ratio_a_to_b: 1.2827, ratio_b_to_a: 0.7796, gap_abs: 23.98 },
  // #172 gap 23.98
  { pair_slug: 'eagle-pass-tx-vs-santa-rosa-petaluma-ca', slug_a: 'eagle-pass-tx', slug_b: 'santa-rosa-petaluma-ca', fips_a: '20580', fips_b: '42220', name_a: "Eagle Pass, TX", name_b: "Santa Rosa, CA", state_a: 'TX', state_b: 'CA', rpp_a: 83.805, rpp_b: 107.784, ratio_a_to_b: 1.2861, ratio_b_to_a: 0.7775, gap_abs: 23.98 },
  // #173 gap 23.97
  { pair_slug: 'kahului-wailuku-hi-vs-wildwood-the-villages-fl', slug_a: 'kahului-wailuku-hi', slug_b: 'wildwood-the-villages-fl', fips_a: '27980', fips_b: '48680', name_a: "Kahului, HI", name_b: "Wildwood, FL", state_a: 'HI', state_b: 'FL', rpp_a: 109.393, rpp_b: 85.424, ratio_a_to_b: 0.7809, ratio_b_to_a: 1.2806, gap_abs: 23.97 },
  // #174 gap 23.95
  { pair_slug: 'dothan-al-vs-santa-rosa-petaluma-ca', slug_a: 'dothan-al', slug_b: 'santa-rosa-petaluma-ca', fips_a: '20020', fips_b: '42220', name_a: "Dothan, AL", name_b: "Santa Rosa, CA", state_a: 'AL', state_b: 'CA', rpp_a: 83.833, rpp_b: 107.784, ratio_a_to_b: 1.2857, ratio_b_to_a: 0.7778, gap_abs: 23.95 },
  // #175 gap 23.94
  { pair_slug: 'houma-bayou-cane-thibodaux-la-vs-salinas-ca', slug_a: 'houma-bayou-cane-thibodaux-la', slug_b: 'salinas-ca', fips_a: '26380', fips_b: '41500', name_a: "Houma, LA", name_b: "Salinas, CA", state_a: 'LA', state_b: 'CA', rpp_a: 85.103, rpp_b: 109.042, ratio_a_to_b: 1.2813, ratio_b_to_a: 0.7805, gap_abs: 23.94 },
  // #176 gap 23.83
  { pair_slug: 'san-luis-obispo-paso-robles-ca-vs-shreveport-bossier-city-la', slug_a: 'san-luis-obispo-paso-robles-ca', slug_b: 'shreveport-bossier-city-la', fips_a: '42020', fips_b: '43340', name_a: "San Luis Obispo, CA", name_b: "Shreveport, LA", state_a: 'CA', state_b: 'LA', rpp_a: 108.596, rpp_b: 84.766, ratio_a_to_b: 0.7806, ratio_b_to_a: 1.2811, gap_abs: 23.83 },
  // #177 gap 23.81
  { pair_slug: 'boston-cambridge-newton-ma-nh-vs-hammond-la', slug_a: 'boston-cambridge-newton-ma-nh', slug_b: 'hammond-la', fips_a: '14460', fips_b: '25220', name_a: "Boston, MA", name_b: "Hammond, LA", state_a: 'MA', state_b: 'LA', rpp_a: 108.266, rpp_b: 84.46, ratio_a_to_b: 0.7801, ratio_b_to_a: 1.2819, gap_abs: 23.81 },
  // #178 gap 23.78
  { pair_slug: 'houma-bayou-cane-thibodaux-la-vs-washington-arlington-alexandria-dc-va-md-wv', slug_a: 'houma-bayou-cane-thibodaux-la', slug_b: 'washington-arlington-alexandria-dc-va-md-wv', fips_a: '26380', fips_b: '47900', name_a: "Houma, LA", name_b: "Washington, DC", state_a: 'LA', state_b: 'DC', rpp_a: 85.103, rpp_b: 108.884, ratio_a_to_b: 1.2794, ratio_b_to_a: 0.7816, gap_abs: 23.78 },
  // #179 gap 23.78
  { pair_slug: 'florence-muscle-shoals-al-vs-san-luis-obispo-paso-robles-ca', slug_a: 'florence-muscle-shoals-al', slug_b: 'san-luis-obispo-paso-robles-ca', fips_a: '22520', fips_b: '42020', name_a: "Florence, AL", name_b: "San Luis Obispo, CA", state_a: 'AL', state_b: 'CA', rpp_a: 84.817, rpp_b: 108.596, ratio_a_to_b: 1.2804, ratio_b_to_a: 0.781, gap_abs: 23.78 },
  // #180 gap 23.77
  { pair_slug: 'santa-rosa-petaluma-ca-vs-texarkana-tx-ar', slug_a: 'santa-rosa-petaluma-ca', slug_b: 'texarkana-tx-ar', fips_a: '42220', fips_b: '45500', name_a: "Santa Rosa, CA", name_b: "Texarkana, TX", state_a: 'CA', state_b: 'TX', rpp_a: 107.784, rpp_b: 84.012, ratio_a_to_b: 0.7794, ratio_b_to_a: 1.283, gap_abs: 23.77 },
  // #181 gap 23.71
  { pair_slug: 'shreveport-bossier-city-la-vs-vallejo-ca', slug_a: 'shreveport-bossier-city-la', slug_b: 'vallejo-ca', fips_a: '43340', fips_b: '46700', name_a: "Shreveport, LA", name_b: "Vallejo, CA", state_a: 'LA', state_b: 'CA', rpp_a: 84.766, rpp_b: 108.479, ratio_a_to_b: 1.2797, ratio_b_to_a: 0.7814, gap_abs: 23.71 },
  // #182 gap 23.70
  { pair_slug: 'houma-bayou-cane-thibodaux-la-vs-santa-maria-santa-barbara-ca', slug_a: 'houma-bayou-cane-thibodaux-la', slug_b: 'santa-maria-santa-barbara-ca', fips_a: '26380', fips_b: '42200', name_a: "Houma, LA", name_b: "Santa Maria, CA", state_a: 'LA', state_b: 'CA', rpp_a: 85.103, rpp_b: 108.798, ratio_a_to_b: 1.2784, ratio_b_to_a: 0.7822, gap_abs: 23.7 },
  // #183 gap 23.66
  { pair_slug: 'florence-muscle-shoals-al-vs-vallejo-ca', slug_a: 'florence-muscle-shoals-al', slug_b: 'vallejo-ca', fips_a: '22520', fips_b: '46700', name_a: "Florence, AL", name_b: "Vallejo, CA", state_a: 'AL', state_b: 'CA', rpp_a: 84.817, rpp_b: 108.479, ratio_a_to_b: 1.279, ratio_b_to_a: 0.7819, gap_abs: 23.66 },
  // #184 gap 23.62
  { pair_slug: 'salinas-ca-vs-wildwood-the-villages-fl', slug_a: 'salinas-ca', slug_b: 'wildwood-the-villages-fl', fips_a: '41500', fips_b: '48680', name_a: "Salinas, CA", name_b: "Wildwood, FL", state_a: 'CA', state_b: 'FL', rpp_a: 109.042, rpp_b: 85.424, ratio_a_to_b: 0.7834, ratio_b_to_a: 1.2765, gap_abs: 23.62 },
  // #185 gap 23.52
  { pair_slug: 'enid-ok-vs-santa-rosa-petaluma-ca', slug_a: 'enid-ok', slug_b: 'santa-rosa-petaluma-ca', fips_a: '21420', fips_b: '42220', name_a: "Enid, OK *", name_b: "Santa Rosa, CA", state_a: 'OK', state_b: 'CA', rpp_a: 84.269, rpp_b: 107.784, ratio_a_to_b: 1.279, ratio_b_to_a: 0.7818, gap_abs: 23.52 },
  // #186 gap 23.50
  { pair_slug: 'boston-cambridge-newton-ma-nh-vs-shreveport-bossier-city-la', slug_a: 'boston-cambridge-newton-ma-nh', slug_b: 'shreveport-bossier-city-la', fips_a: '14460', fips_b: '43340', name_a: "Boston, MA", name_b: "Shreveport, LA", state_a: 'MA', state_b: 'LA', rpp_a: 108.266, rpp_b: 84.766, ratio_a_to_b: 0.7829, ratio_b_to_a: 1.2772, gap_abs: 23.5 },
  // #187 gap 23.49
  { pair_slug: 'houma-bayou-cane-thibodaux-la-vs-san-luis-obispo-paso-robles-ca', slug_a: 'houma-bayou-cane-thibodaux-la', slug_b: 'san-luis-obispo-paso-robles-ca', fips_a: '26380', fips_b: '42020', name_a: "Houma, LA", name_b: "San Luis Obispo, CA", state_a: 'LA', state_b: 'CA', rpp_a: 85.103, rpp_b: 108.596, ratio_a_to_b: 1.2761, ratio_b_to_a: 0.7837, gap_abs: 23.49 },
  // #188 gap 23.46
  { pair_slug: 'washington-arlington-alexandria-dc-va-md-wv-vs-wildwood-the-villages-fl', slug_a: 'washington-arlington-alexandria-dc-va-md-wv', slug_b: 'wildwood-the-villages-fl', fips_a: '47900', fips_b: '48680', name_a: "Washington, DC", name_b: "Wildwood, FL", state_a: 'DC', state_b: 'FL', rpp_a: 108.884, rpp_b: 85.424, ratio_a_to_b: 0.7845, ratio_b_to_a: 1.2746, gap_abs: 23.46 },
  // #189 gap 23.45
  { pair_slug: 'boston-cambridge-newton-ma-nh-vs-florence-muscle-shoals-al', slug_a: 'boston-cambridge-newton-ma-nh', slug_b: 'florence-muscle-shoals-al', fips_a: '14460', fips_b: '22520', name_a: "Boston, MA", name_b: "Florence, AL", state_a: 'MA', state_b: 'AL', rpp_a: 108.266, rpp_b: 84.817, ratio_a_to_b: 0.7834, ratio_b_to_a: 1.2765, gap_abs: 23.45 },
  // #190 gap 23.38
  { pair_slug: 'houma-bayou-cane-thibodaux-la-vs-vallejo-ca', slug_a: 'houma-bayou-cane-thibodaux-la', slug_b: 'vallejo-ca', fips_a: '26380', fips_b: '46700', name_a: "Houma, LA", name_b: "Vallejo, CA", state_a: 'LA', state_b: 'CA', rpp_a: 85.103, rpp_b: 108.479, ratio_a_to_b: 1.2747, ratio_b_to_a: 0.7845, gap_abs: 23.38 },
  // #191 gap 23.37
  { pair_slug: 'santa-maria-santa-barbara-ca-vs-wildwood-the-villages-fl', slug_a: 'santa-maria-santa-barbara-ca', slug_b: 'wildwood-the-villages-fl', fips_a: '42200', fips_b: '48680', name_a: "Santa Maria, CA", name_b: "Wildwood, FL", state_a: 'CA', state_b: 'FL', rpp_a: 108.798, rpp_b: 85.424, ratio_a_to_b: 0.7852, ratio_b_to_a: 1.2736, gap_abs: 23.37 },
  // #192 gap 23.32
  { pair_slug: 'hammond-la-vs-santa-rosa-petaluma-ca', slug_a: 'hammond-la', slug_b: 'santa-rosa-petaluma-ca', fips_a: '25220', fips_b: '42220', name_a: "Hammond, LA", name_b: "Santa Rosa, CA", state_a: 'LA', state_b: 'CA', rpp_a: 84.46, rpp_b: 107.784, ratio_a_to_b: 1.2762, ratio_b_to_a: 0.7836, gap_abs: 23.32 },
  // #193 gap 23.27
  { pair_slug: 'bridgeport-stamford-danbury-ct-metropolitan-statistical-area-vs-monroe-la', slug_a: 'bridgeport-stamford-danbury-ct-metropolitan-statistical-area', slug_b: 'monroe-la', fips_a: '14860', fips_b: '33740', name_a: "Bridgeport, CT Metropolitan Statistical Area", name_b: "Monroe, LA", state_a: 'CT', state_b: 'LA', rpp_a: 106.864, rpp_b: 83.597, ratio_a_to_b: 0.7823, ratio_b_to_a: 1.2783, gap_abs: 23.27 },
  // #194 gap 23.17
  { pair_slug: 'san-luis-obispo-paso-robles-ca-vs-wildwood-the-villages-fl', slug_a: 'san-luis-obispo-paso-robles-ca', slug_b: 'wildwood-the-villages-fl', fips_a: '42020', fips_b: '48680', name_a: "San Luis Obispo, CA", name_b: "Wildwood, FL", state_a: 'CA', state_b: 'FL', rpp_a: 108.596, rpp_b: 85.424, ratio_a_to_b: 0.7866, ratio_b_to_a: 1.2713, gap_abs: 23.17 },
  // #195 gap 23.16
  { pair_slug: 'boston-cambridge-newton-ma-nh-vs-houma-bayou-cane-thibodaux-la', slug_a: 'boston-cambridge-newton-ma-nh', slug_b: 'houma-bayou-cane-thibodaux-la', fips_a: '14460', fips_b: '26380', name_a: "Boston, MA", name_b: "Houma, LA", state_a: 'MA', state_b: 'LA', rpp_a: 108.266, rpp_b: 85.103, ratio_a_to_b: 0.7861, ratio_b_to_a: 1.2722, gap_abs: 23.16 },
  // #196 gap 23.07
  { pair_slug: 'monroe-la-vs-sacramento-roseville-folsom-ca', slug_a: 'monroe-la', slug_b: 'sacramento-roseville-folsom-ca', fips_a: '33740', fips_b: '40900', name_a: "Monroe, LA", name_b: "Sacramento, CA", state_a: 'LA', state_b: 'CA', rpp_a: 83.597, rpp_b: 106.67, ratio_a_to_b: 1.276, ratio_b_to_a: 0.7837, gap_abs: 23.07 },
  // #197 gap 23.06
  { pair_slug: 'bridgeport-stamford-danbury-ct-metropolitan-statistical-area-vs-eagle-pass-tx', slug_a: 'bridgeport-stamford-danbury-ct-metropolitan-statistical-area', slug_b: 'eagle-pass-tx', fips_a: '14860', fips_b: '20580', name_a: "Bridgeport, CT Metropolitan Statistical Area", name_b: "Eagle Pass, TX", state_a: 'CT', state_b: 'TX', rpp_a: 106.864, rpp_b: 83.805, ratio_a_to_b: 0.7842, ratio_b_to_a: 1.2752, gap_abs: 23.06 },
  // #198 gap 23.05
  { pair_slug: 'vallejo-ca-vs-wildwood-the-villages-fl', slug_a: 'vallejo-ca', slug_b: 'wildwood-the-villages-fl', fips_a: '46700', fips_b: '48680', name_a: "Vallejo, CA", name_b: "Wildwood, FL", state_a: 'CA', state_b: 'FL', rpp_a: 108.479, rpp_b: 85.424, ratio_a_to_b: 0.7875, ratio_b_to_a: 1.2699, gap_abs: 23.05 },
  // #199 gap 23.03
  { pair_slug: 'bridgeport-stamford-danbury-ct-metropolitan-statistical-area-vs-dothan-al', slug_a: 'bridgeport-stamford-danbury-ct-metropolitan-statistical-area', slug_b: 'dothan-al', fips_a: '14860', fips_b: '20020', name_a: "Bridgeport, CT Metropolitan Statistical Area", name_b: "Dothan, AL", state_a: 'CT', state_b: 'AL', rpp_a: 106.864, rpp_b: 83.833, ratio_a_to_b: 0.7845, ratio_b_to_a: 1.2747, gap_abs: 23.03 },
  // #200 gap 23.02
  { pair_slug: 'santa-rosa-petaluma-ca-vs-shreveport-bossier-city-la', slug_a: 'santa-rosa-petaluma-ca', slug_b: 'shreveport-bossier-city-la', fips_a: '42220', fips_b: '43340', name_a: "Santa Rosa, CA", name_b: "Shreveport, LA", state_a: 'CA', state_b: 'LA', rpp_a: 107.784, rpp_b: 84.766, ratio_a_to_b: 0.7864, ratio_b_to_a: 1.2715, gap_abs: 23.02 },
];

const BY_PAIR_SLUG: Map<string, EquivalentPair> = new Map(
  EQUIVALENT_PAIRS.map((p) => [p.pair_slug, p]),
);

export function getEquivalentPair(pairSlug: string): EquivalentPair | undefined {
  return BY_PAIR_SLUG.get(pairSlug);
}

export function getAllPairSlugs(): string[] {
  return EQUIVALENT_PAIRS.map((p) => p.pair_slug);
}

/**
 * Compute the destination salary needed to match a source salary's buying power.
 * direction='a-to-b' uses ratio_a_to_b (source = A, destination = B).
 */
export function equivalentSalary(
  pair: EquivalentPair,
  sourceSalary: number,
  direction: 'a-to-b' | 'b-to-a',
): number {
  const ratio = direction === 'a-to-b' ? pair.ratio_a_to_b : pair.ratio_b_to_a;
  return Math.round(sourceSalary * ratio);
}
