#!/usr/bin/env tsx
/**
 * Build lib/pce-deflator.ts from data/raw/bea-pce/PCEPI.csv (FRED PCEPI).
 *
 * Source: BEA NIPA Table 1.1.4 → FRED series PCEPI (Personal Consumption
 *         Expenditures: Chain-type Price Index, monthly, 2017=100, SA).
 *
 * Veto #7 status: CLEAR — primary BEA series via FRED mirror.
 *
 * Output:
 *   lib/pce-deflator.ts — monthly + yearly arrays + real_value helper
 *
 * Usage: npx tsx scripts/build-pce-deflator.ts
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const SRC = join(process.cwd(), 'data/raw/bea-pce/PCEPI.csv');
const DST = join(process.cwd(), 'lib/pce-deflator.ts');

type Row = { date: string; year: number; month: number; value: number };

function parse(): Row[] {
  const raw = readFileSync(SRC, 'utf8');
  const lines = raw.split(/\r?\n/).filter(Boolean);
  const rows: Row[] = [];
  for (let i = 1; i < lines.length; i++) {
    const [date, val] = lines[i].split(',');
    if (!date || !val) continue;
    const v = parseFloat(val);
    if (!Number.isFinite(v)) continue;
    const [y, m] = date.split('-');
    rows.push({ date, year: parseInt(y, 10), month: parseInt(m, 10), value: v });
  }
  return rows;
}

function annual(rows: Row[]): Array<{ year: number; value: number }> {
  const by: Record<number, number[]> = {};
  for (const r of rows) {
    (by[r.year] ??= []).push(r.value);
  }
  return Object.keys(by)
    .map(Number)
    .sort((a, b) => a - b)
    .map((year) => {
      const arr = by[year];
      const avg = arr.reduce((s, x) => s + x, 0) / arr.length;
      return { year, value: Math.round(avg * 1000) / 1000 };
    });
}

function emit() {
  const monthly = parse();
  const yearly = annual(monthly);

  const lastFullYear = yearly.findLast((r) => {
    const monthsThisYear = monthly.filter((m) => m.year === r.year).length;
    return monthsThisYear === 12;
  });

  let out = `// AUTO-GENERATED by scripts/build-pce-deflator.ts — do not edit by hand.
// Source: FRED series PCEPI (BEA NIPA Table 1.1.4).
// Personal Consumption Expenditures: Chain-type Price Index, 2017=100, SA.
// Last refresh: ${new Date().toISOString().slice(0, 10)}
// Coverage: ${monthly[0].date} → ${monthly[monthly.length - 1].date} (${monthly.length} months)
// Last full year: ${lastFullYear?.year}

export const PCE_BASE_YEAR = 2017;

/**
 * Annual average PCE Price Index, 2017 = 100.
 * Use for "real-vs-nominal" comparisons.
 */
export const PCE_DEFLATOR_YEARLY: ReadonlyArray<{ year: number; value: number }> = [
${yearly.map((r) => `  { year: ${r.year}, value: ${r.value} },`).join('\n')}
];

const YEARLY_BY_YEAR: Map<number, number> = new Map(
  PCE_DEFLATOR_YEARLY.map((r) => [r.year, r.value]),
);

/**
 * Convert a nominal dollar amount from \`fromYear\` to equivalent buying power in \`toYear\`.
 * Returns NaN if either year is outside coverage.
 *
 * Example: \`realValue(70_000, 2008, 2024)\` → ~98_000
 */
export function realValue(nominal: number, fromYear: number, toYear: number): number {
  const from = YEARLY_BY_YEAR.get(fromYear);
  const to = YEARLY_BY_YEAR.get(toYear);
  if (from === undefined || to === undefined) return NaN;
  return nominal * (to / from);
}

/**
 * Inflation factor between two years (toYear / fromYear, in %).
 * Example: \`inflationPct(2008, 2024)\` → ~40.5 (cumulative %)
 */
export function inflationPct(fromYear: number, toYear: number): number {
  const from = YEARLY_BY_YEAR.get(fromYear);
  const to = YEARLY_BY_YEAR.get(toYear);
  if (from === undefined || to === undefined) return NaN;
  return ((to - from) / from) * 100;
}

/**
 * Get the PCE deflator value for a specific year (annual average).
 */
export function pceForYear(year: number): number | undefined {
  return YEARLY_BY_YEAR.get(year);
}

/**
 * Monthly PCE Price Index — full series. Use for fine-grained chart rendering.
 */
export const PCE_DEFLATOR_MONTHLY: ReadonlyArray<{ date: string; value: number }> = [
${monthly.map((r) => `  { date: '${r.date}', value: ${r.value} },`).join('\n')}
];
`;

  writeFileSync(DST, out, 'utf8');
  console.log(`[B-4] wrote ${DST}`);
  console.log(`  monthly: ${monthly.length} rows`);
  console.log(`  yearly: ${yearly.length} rows (${yearly[0].year}-${yearly[yearly.length - 1].year})`);
  console.log(`  last full year: ${lastFullYear?.year} = ${lastFullYear?.value}`);
}

emit();
