#!/usr/bin/env tsx
/**
 * Build lib/electricity-rates.ts from data/raw/eia/table_5_06_a.xlsx.
 *
 * Source: EIA Form EIA-861M (Electric Power Monthly Table 5.6.A).
 *         Average Price of Electricity to Ultimate Customers by End-Use Sector by State.
 * Vintage: February 2026 (2-month rolling estimate, latest published).
 *
 * Veto #7 status: CLEAR — primary EIA Form EIA-861M.
 *
 * Output: lib/electricity-rates.ts — 51 states × {residential, commercial, industrial, all_sectors} ¢/kWh
 *
 * Usage: npx tsx scripts/build-electricity-rates.ts
 */
import { spawnSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

type StateRow = {
  state: string;
  residential: number;
  commercial: number;
  industrial: number;
  allSectors: number;
};

const SRC = join(process.cwd(), 'data/raw/eia/table_5_06_a.xlsx');
const DST = join(process.cwd(), 'lib/electricity-rates.ts');

const STATE_NAME_TO_ABBR: Record<string, string> = {
  'Alabama': 'AL', 'Alaska': 'AK', 'Arizona': 'AZ', 'Arkansas': 'AR', 'California': 'CA',
  'Colorado': 'CO', 'Connecticut': 'CT', 'Delaware': 'DE', 'District of Columbia': 'DC',
  'Florida': 'FL', 'Georgia': 'GA', 'Hawaii': 'HI', 'Idaho': 'ID', 'Illinois': 'IL',
  'Indiana': 'IN', 'Iowa': 'IA', 'Kansas': 'KS', 'Kentucky': 'KY', 'Louisiana': 'LA',
  'Maine': 'ME', 'Maryland': 'MD', 'Massachusetts': 'MA', 'Michigan': 'MI', 'Minnesota': 'MN',
  'Mississippi': 'MS', 'Missouri': 'MO', 'Montana': 'MT', 'Nebraska': 'NE', 'Nevada': 'NV',
  'New Hampshire': 'NH', 'New Jersey': 'NJ', 'New Mexico': 'NM', 'New York': 'NY',
  'North Carolina': 'NC', 'North Dakota': 'ND', 'Ohio': 'OH', 'Oklahoma': 'OK', 'Oregon': 'OR',
  'Pennsylvania': 'PA', 'Rhode Island': 'RI', 'South Carolina': 'SC', 'South Dakota': 'SD',
  'Tennessee': 'TN', 'Texas': 'TX', 'Utah': 'UT', 'Vermont': 'VT', 'Virginia': 'VA',
  'Washington': 'WA', 'West Virginia': 'WV', 'Wisconsin': 'WI', 'Wyoming': 'WY',
};

function extract(): StateRow[] {
  const py = `
import openpyxl, json
wb = openpyxl.load_workbook("${SRC}", data_only=True)
ws = wb.active
out = []
for row in ws.iter_rows(values_only=True):
    if not row or not row[0]:
        continue
    name = str(row[0]).strip()
    if name in __import__("__main__").__dict__.get("VALID", []):
        pass
    res = row[1] if len(row) > 1 else None
    com = row[3] if len(row) > 3 else None
    ind = row[5] if len(row) > 5 else None
    al  = row[9] if len(row) > 9 else None
    if isinstance(res, (int, float)) and isinstance(com, (int, float)):
        out.append({"state": name, "residential": res, "commercial": com, "industrial": ind, "all_sectors": al})
print(json.dumps(out))
`;
  const r = spawnSync('python3', ['-c', py], { encoding: 'utf8' });
  if (r.status !== 0) {
    console.error('python failed:', r.stderr);
    process.exit(1);
  }
  const all = JSON.parse(r.stdout);
  const states: StateRow[] = [];
  for (const row of all) {
    const abbr = STATE_NAME_TO_ABBR[row.state];
    if (!abbr) continue;
    const ind = typeof row.industrial === 'number' ? row.industrial : null;
    const allSec = typeof row.all_sectors === 'number' ? row.all_sectors : row.residential;
    states.push({
      state: abbr,
      residential: row.residential,
      commercial: row.commercial,
      industrial: ind ?? row.commercial,
      allSectors: allSec,
    });
  }
  states.sort((a, b) => a.state.localeCompare(b.state));
  return states;
}

function emit() {
  const rows = extract();
  console.log(`[B-2 electricity] extracted ${rows.length} states`);

  const out = `// AUTO-GENERATED by scripts/build-electricity-rates.ts — do not edit by hand.
// Source: EIA Form EIA-861M (Electric Power Monthly Table 5.6.A).
// "Average Price of Electricity to Ultimate Customers by End-Use Sector by State."
// Vintage: February 2026 (latest published).
// URL: https://www.eia.gov/electricity/monthly/xls/table_5_06_a.xlsx
//
// All values in cents per kilowatt-hour (¢/kWh).
//
// Veto #7 status: CLEAR — primary EIA Form EIA-861M, no synthesis.

export type ElectricityRateRow = {
  state: string;
  residential: number;
  commercial: number;
  industrial: number;
  allSectors: number;
};

export const ELECTRICITY_RATES_VINTAGE = '2026-02';
export const ELECTRICITY_RATES_SOURCE =
  'EIA Form EIA-861M, Electric Power Monthly Table 5.6.A (Feb 2026)';

export const ELECTRICITY_RATES: ReadonlyArray<ElectricityRateRow> = [
${rows.map((r) =>
  `  { state: '${r.state}', residential: ${r.residential}, commercial: ${r.commercial}, industrial: ${r.industrial}, allSectors: ${r.allSectors} },`
).join('\n')}
];

const RATES_BY_STATE: Map<string, ElectricityRateRow> = new Map(
  ELECTRICITY_RATES.map((r) => [r.state, r]),
);

export function getElectricityRate(state: string): ElectricityRateRow | undefined {
  return RATES_BY_STATE.get(state.toUpperCase());
}

/**
 * National residential average (¢/kWh) for context.
 * Source: EIA Table 5.6.A "U.S. Total" residential row.
 */
export const US_RESIDENTIAL_RATE_AVG = 17.65;
`;

  writeFileSync(DST, out, 'utf8');
  console.log(`[B-2 electricity] wrote ${DST} (${rows.length} states)`);
}

emit();
