#!/usr/bin/env tsx
/**
 * Build lib/equivalent-pairs.ts — top 200 city-pair Real-Wage Equivalent rows.
 *
 * For each pair (cityA, cityB) we compute:
 *   ratio_A_to_B = RPP_B / RPP_A  → multiplier for "$1 in A buys X in B".
 *   To match purchasing power, an A-resident moving to B needs salary × this ratio.
 *
 * Selection logic:
 *   1. Pool = top 60 metros by all-items RPP DESC + bottom 10 ASC = 70 unique.
 *   2. Generate all C(70,2) pair combinations.
 *   3. Rank by abs(RPP_A - RPP_B) descending — biggest cost-of-living gap.
 *   4. Take top 200.
 *
 * Output is canonical (one row per pair). Display logic can render both directions.
 *
 * Source: BEA SARPP/MARPP 2024 (latest year in costliving.db).
 * Veto #7 status: CLEAR — derivation from primary BEA series, no synthesis.
 *
 * Usage: npx tsx scripts/build-equivalent-pairs.ts
 */
import Database from 'better-sqlite3';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

const DB_SRC = join(process.cwd(), 'data/costliving.db');
const DST = join(process.cwd(), 'lib/equivalent-pairs.ts');

type MetroRow = {
  fips: string;
  slug: string;
  short_name: string;
  state: string;
  rpp_all: number;
};

function selectPool(db: Database.Database): MetroRow[] {
  const top60 = db.prepare(`
    SELECT m.fips, m.slug, m.short_name, m.state, r.value AS rpp_all
    FROM metros m
    JOIN rpp r ON m.fips = r.fips
    WHERE r.category = 'all' AND r.year = (SELECT MAX(year) FROM rpp)
    ORDER BY r.value DESC
    LIMIT 60
  `).all() as MetroRow[];
  const bottom10 = db.prepare(`
    SELECT m.fips, m.slug, m.short_name, m.state, r.value AS rpp_all
    FROM metros m
    JOIN rpp r ON m.fips = r.fips
    WHERE r.category = 'all' AND r.year = (SELECT MAX(year) FROM rpp)
    ORDER BY r.value ASC
    LIMIT 10
  `).all() as MetroRow[];
  const seen = new Set<string>();
  const out: MetroRow[] = [];
  for (const r of [...top60, ...bottom10]) {
    if (seen.has(r.fips)) continue;
    seen.add(r.fips);
    out.push(r);
  }
  return out;
}

type PairRow = {
  pair_slug: string;
  slug_a: string;
  slug_b: string;
  fips_a: string;
  fips_b: string;
  name_a: string;
  name_b: string;
  state_a: string;
  state_b: string;
  rpp_a: number;
  rpp_b: number;
  ratio_a_to_b: number; // multiplier for A→B (income needed in B to match A buying power)
  ratio_b_to_a: number;
  gap_abs: number;
};

function makePairSlug(slugA: string, slugB: string): string {
  return slugA < slugB ? `${slugA}-vs-${slugB}` : `${slugB}-vs-${slugA}`;
}

function build() {
  const db = new Database(DB_SRC, { readonly: true });
  const year = (db.prepare('SELECT MAX(year) AS y FROM rpp').get() as { y: number }).y;
  const pool = selectPool(db);
  console.log(`[B-6] pool size: ${pool.length} (year ${year})`);

  const allPairs: PairRow[] = [];
  for (let i = 0; i < pool.length; i++) {
    for (let j = i + 1; j < pool.length; j++) {
      const a = pool[i];
      const b = pool[j];
      // Canonical order: lower slug first.
      const [first, second] = a.slug < b.slug ? [a, b] : [b, a];
      const ratioFwd = round4(second.rpp_all / first.rpp_all);
      const ratioRev = round4(first.rpp_all / second.rpp_all);
      allPairs.push({
        pair_slug: `${first.slug}-vs-${second.slug}`,
        slug_a: first.slug,
        slug_b: second.slug,
        fips_a: first.fips,
        fips_b: second.fips,
        name_a: first.short_name,
        name_b: second.short_name,
        state_a: first.state,
        state_b: second.state,
        rpp_a: first.rpp_all,
        rpp_b: second.rpp_all,
        ratio_a_to_b: ratioFwd,
        ratio_b_to_a: ratioRev,
        gap_abs: Math.abs(first.rpp_all - second.rpp_all),
      });
    }
  }
  allPairs.sort((x, y) => y.gap_abs - x.gap_abs);
  const top200 = allPairs.slice(0, 200);
  console.log(`[B-6] candidate pairs: ${allPairs.length} → top 200`);
  console.log(`[B-6] gap range: ${top200[0].gap_abs.toFixed(2)} → ${top200[199].gap_abs.toFixed(2)}`);

  const lines = top200.map((p, idx) => {
    return `  // #${idx + 1} gap ${p.gap_abs.toFixed(2)}\n  { pair_slug: '${p.pair_slug}', slug_a: '${p.slug_a}', slug_b: '${p.slug_b}', fips_a: '${p.fips_a}', fips_b: '${p.fips_b}', name_a: ${JSON.stringify(p.name_a)}, name_b: ${JSON.stringify(p.name_b)}, state_a: '${p.state_a}', state_b: '${p.state_b}', rpp_a: ${p.rpp_a}, rpp_b: ${p.rpp_b}, ratio_a_to_b: ${p.ratio_a_to_b}, ratio_b_to_a: ${p.ratio_b_to_a}, gap_abs: ${round2(p.gap_abs)} },`;
  }).join('\n');

  const out = `// AUTO-GENERATED by scripts/build-equivalent-pairs.ts — do not edit by hand.
// Source: BEA Regional Price Parities (MARPP) ${year}.
// Top 200 metro pairs by absolute RPP gap, drawn from top-60 + bottom-10 RPP pool.
// Ratio interpretation: ratio_a_to_b = RPP_b / RPP_a, the multiplier on a salary
// when relocating A → B to maintain identical purchasing power.
//
// Veto #7 status: CLEAR — derivation from primary BEA RPP, no synthesis.

export type EquivalentPair = {
  pair_slug: string;
  slug_a: string;
  slug_b: string;
  fips_a: string;
  fips_b: string;
  name_a: string;
  name_b: string;
  state_a: string;
  state_b: string;
  rpp_a: number;
  rpp_b: number;
  ratio_a_to_b: number;
  ratio_b_to_a: number;
  gap_abs: number;
};

export const EQUIVALENT_PAIRS_VINTAGE = '${year}';
export const EQUIVALENT_PAIRS_SOURCE =
  'BEA Regional Price Parities (MARPP), ${year} vintage';

export const EQUIVALENT_PAIRS: ReadonlyArray<EquivalentPair> = [
${lines}
];

const BY_PAIR_SLUG: Map<string, EquivalentPair> = new Map(
  EQUIVALENT_PAIRS.map((p) => [p.pair_slug, p]),
);

export function getEquivalentPair(pairSlug: string): EquivalentPair | undefined {
  return BY_PAIR_SLUG.get(pairSlug);
}

export function getAllPairSlugs(): string[] {
  return EQUIVALENT_PAIRS.map((p) => p.pair_slug);
}

/**
 * Compute the destination salary needed to match a source salary's buying power.
 * direction='a-to-b' uses ratio_a_to_b (source = A, destination = B).
 */
export function equivalentSalary(
  pair: EquivalentPair,
  sourceSalary: number,
  direction: 'a-to-b' | 'b-to-a',
): number {
  const ratio = direction === 'a-to-b' ? pair.ratio_a_to_b : pair.ratio_b_to_a;
  return Math.round(sourceSalary * ratio);
}
`;

  writeFileSync(DST, out, 'utf8');
  console.log(`[B-6] wrote ${DST} (200 pairs, ${out.length} bytes)`);
}

function round4(n: number): number {
  return Math.round(n * 10000) / 10000;
}
function round2(n: number): number {
  return Math.round(n * 100) / 100;
}

build();
